"""
Tests for generated client classes.
Auto-generated by bin/generate_sdks.rb - DO NOT EDIT
"""

import pytest

import aho_sdk
from aho_sdk import Account, System, Holder, Verifier, Issuer, Schemas, Unauthenticated

class TestSdkModule:
    """Tests for the main aho_sdk module."""

    def test_exports_account(self):
        assert hasattr(aho_sdk, "Account")

    def test_exports_system(self):
        assert hasattr(aho_sdk, "System")

    def test_exports_holder(self):
        assert hasattr(aho_sdk, "Holder")

    def test_exports_verifier(self):
        assert hasattr(aho_sdk, "Verifier")

    def test_exports_issuer(self):
        assert hasattr(aho_sdk, "Issuer")

    def test_exports_schemas(self):
        assert hasattr(aho_sdk, "Schemas")

    def test_exports_unauthenticated(self):
        assert hasattr(aho_sdk, "Unauthenticated")

    def test_exports_page(self):
        assert hasattr(aho_sdk, "Page")

    def test_exports_api_error(self):
        assert hasattr(aho_sdk, "ApiError")

    def test_exports_version(self):
        assert hasattr(aho_sdk, "VERSION")

class TestAccount:
    """Tests for Account client."""

    def test_init_creates_client(self):
        client = Account(api_key="test-key")

        assert client is not None

    def test_init_accepts_custom_base_url(self):
        client = Account(api_key="test-key", base_url="https://custom.com")

        assert client._client._base_url == "https://custom.com"

    def test_has_api_keys_resource(self):
        client = Account(api_key="test-key")

        assert hasattr(client, "api_keys")
        assert hasattr(client.api_keys, "list")
        assert hasattr(client.api_keys, "get")
        assert hasattr(client.api_keys, "update")

    def test_has_regenerate_resource(self):
        client = Account(api_key="test-key")

        assert hasattr(client, "regenerate")
        assert hasattr(client.regenerate, "create")

    def test_has_domains_resource(self):
        client = Account(api_key="test-key")

        assert hasattr(client, "domains")
        assert hasattr(client.domains, "create")
        assert hasattr(client.domains, "list")
        assert hasattr(client.domains, "get")
        assert hasattr(client.domains, "delete")
        assert hasattr(client.domains, "verify")

    def test_has_signing_keys_resource(self):
        client = Account(api_key="test-key")

        assert hasattr(client, "signing_keys")
        assert hasattr(client.signing_keys, "create")
        assert hasattr(client.signing_keys, "list")
        assert hasattr(client.signing_keys, "get")
        assert hasattr(client.signing_keys, "rotate")
        assert hasattr(client.signing_keys, "revoke")
        assert hasattr(client.signing_keys, "certificate")

    def test_has_webhooks_resource(self):
        client = Account(api_key="test-key")

        assert hasattr(client, "webhooks")
        assert hasattr(client.webhooks, "list")
        assert hasattr(client.webhooks, "create")
        assert hasattr(client.webhooks, "get")
        assert hasattr(client.webhooks, "update")
        assert hasattr(client.webhooks, "delete")
        assert hasattr(client.webhooks, "test")

class TestSystem:
    """Tests for System client."""

    def test_init_creates_client(self):
        client = System(api_key="test-key")

        assert client is not None

    def test_init_accepts_custom_base_url(self):
        client = System(api_key="test-key", base_url="https://custom.com")

        assert client._client._base_url == "https://custom.com"

    def test_has_health_resource(self):
        client = System(api_key="test-key")

        assert hasattr(client, "health")
        assert hasattr(client.health, "get")

class TestHolder:
    """Tests for Holder client."""

    def test_init_creates_client(self):
        client = Holder(api_key="test-key")

        assert client is not None

    def test_init_accepts_custom_base_url(self):
        client = Holder(api_key="test-key", base_url="https://custom.com")

        assert client._client._base_url == "https://custom.com"

    def test_has_credentials_resource(self):
        client = Holder(api_key="test-key")

        assert hasattr(client, "credentials")
        assert hasattr(client.credentials, "list")
        assert hasattr(client.credentials, "get")

    def test_has_presentations_resource(self):
        client = Holder(api_key="test-key")

        assert hasattr(client, "presentations")
        assert hasattr(client.presentations, "list")
        assert hasattr(client.presentations, "create")
        assert hasattr(client.presentations, "get")
        assert hasattr(client.presentations, "delete")

class TestVerifier:
    """Tests for Verifier client."""

    def test_init_creates_client(self):
        client = Verifier(api_key="test-key")

        assert client is not None

    def test_init_accepts_custom_base_url(self):
        client = Verifier(api_key="test-key", base_url="https://custom.com")

        assert client._client._base_url == "https://custom.com"

    def test_has_presentations_resource(self):
        client = Verifier(api_key="test-key")

        assert hasattr(client, "presentations")
        assert hasattr(client.presentations, "verify")

    def test_has_dc_sessions_resource(self):
        client = Verifier(api_key="test-key")

        assert hasattr(client, "dc_sessions")
        assert hasattr(client.dc_sessions, "create")
        assert hasattr(client.dc_sessions, "get")
        assert hasattr(client.dc_sessions, "verify")

    def test_has_render_resource(self):
        client = Verifier(api_key="test-key")

        assert hasattr(client, "render")
        assert hasattr(client.render, "list")
        assert hasattr(client.render, "create")

    def test_has_requests_resource(self):
        client = Verifier(api_key="test-key")

        assert hasattr(client, "requests")
        assert hasattr(client.requests, "create")
        assert hasattr(client.requests, "list")
        assert hasattr(client.requests, "get")
        assert hasattr(client.requests, "update")
        assert hasattr(client.requests, "delete")
        assert hasattr(client.requests, "activate")
        assert hasattr(client.requests, "close")
        assert hasattr(client.requests, "qr_code")

    def test_has_responses_resource(self):
        client = Verifier(api_key="test-key")

        assert hasattr(client, "responses")
        assert hasattr(client.responses, "list")
        assert hasattr(client.responses, "get")

class TestIssuer:
    """Tests for Issuer client."""

    def test_init_creates_client(self):
        client = Issuer(api_key="test-key")

        assert client is not None

    def test_init_accepts_custom_base_url(self):
        client = Issuer(api_key="test-key", base_url="https://custom.com")

        assert client._client._base_url == "https://custom.com"

    def test_has_automations_resource(self):
        client = Issuer(api_key="test-key")

        assert hasattr(client, "automations")
        assert hasattr(client.automations, "get_webhook")
        assert hasattr(client.automations, "create_webhook")
        assert hasattr(client.automations, "delete_webhook")
        assert hasattr(client.automations, "create")
        assert hasattr(client.automations, "list")
        assert hasattr(client.automations, "get")
        assert hasattr(client.automations, "update")
        assert hasattr(client.automations, "delete")
        assert hasattr(client.automations, "trigger")
        assert hasattr(client.automations, "pause")
        assert hasattr(client.automations, "resume")

    def test_has_credentials_resource(self):
        client = Issuer(api_key="test-key")

        assert hasattr(client, "credentials")
        assert hasattr(client.credentials, "create")
        assert hasattr(client.credentials, "list")
        assert hasattr(client.credentials, "get")
        assert hasattr(client.credentials, "revoke")
        assert hasattr(client.credentials, "suspend")
        assert hasattr(client.credentials, "reinstate")
        assert hasattr(client.credentials, "status")
        assert hasattr(client.credentials, "history")

    def test_has_revoke_batch_resource(self):
        client = Issuer(api_key="test-key")

        assert hasattr(client, "revoke_batch")
        assert hasattr(client.revoke_batch, "create")

    def test_has_suspend_batch_resource(self):
        client = Issuer(api_key="test-key")

        assert hasattr(client, "suspend_batch")
        assert hasattr(client.suspend_batch, "create")

    def test_has_reinstate_batch_resource(self):
        client = Issuer(api_key="test-key")

        assert hasattr(client, "reinstate_batch")
        assert hasattr(client.reinstate_batch, "create")

    def test_has_data_source_mappings_resource(self):
        client = Issuer(api_key="test-key")

        assert hasattr(client, "data_source_mappings")
        assert hasattr(client.data_source_mappings, "create")
        assert hasattr(client.data_source_mappings, "list")
        assert hasattr(client.data_source_mappings, "get")
        assert hasattr(client.data_source_mappings, "update")
        assert hasattr(client.data_source_mappings, "delete")

    def test_has_data_sources_resource(self):
        client = Issuer(api_key="test-key")

        assert hasattr(client, "data_sources")
        assert hasattr(client.data_sources, "create")
        assert hasattr(client.data_sources, "list")
        assert hasattr(client.data_sources, "get")
        assert hasattr(client.data_sources, "update")
        assert hasattr(client.data_sources, "delete")
        assert hasattr(client.data_sources, "test")

    def test_has_offers_resource(self):
        client = Issuer(api_key="test-key")

        assert hasattr(client, "offers")
        assert hasattr(client.offers, "list")
        assert hasattr(client.offers, "create")
        assert hasattr(client.offers, "get")
        assert hasattr(client.offers, "revoke")

    def test_has_schemas_resource(self):
        client = Issuer(api_key="test-key")

        assert hasattr(client, "schemas")
        assert hasattr(client.schemas, "create")
        assert hasattr(client.schemas, "list")
        assert hasattr(client.schemas, "get")
        assert hasattr(client.schemas, "update")
        assert hasattr(client.schemas, "delete")
        assert hasattr(client.schemas, "activate")
        assert hasattr(client.schemas, "archive")

    def test_has_verify_resource(self):
        client = Issuer(api_key="test-key")

        assert hasattr(client, "verify")
        assert hasattr(client.verify, "get")
        assert hasattr(client.verify, "create")

class TestSchemas:
    """Tests for Schemas client."""

    def test_init_creates_client(self):
        client = Schemas(api_key="test-key")

        assert client is not None

    def test_init_accepts_custom_base_url(self):
        client = Schemas(api_key="test-key", base_url="https://custom.com")

        assert client._client._base_url == "https://custom.com"

    def test_has_render_templates_resource(self):
        client = Schemas(api_key="test-key")

        assert hasattr(client, "render_templates")
        assert hasattr(client.render_templates, "list")
        assert hasattr(client.render_templates, "create")
        assert hasattr(client.render_templates, "get")
        assert hasattr(client.render_templates, "update")
        assert hasattr(client.render_templates, "delete")
        assert hasattr(client.render_templates, "validate")

class TestUnauthenticated:
    """Tests for Unauthenticated client."""

    def test_init_creates_client(self):
        client = Unauthenticated()

        assert client is not None

    def test_init_accepts_custom_base_url(self):
        client = Unauthenticated(base_url="https://custom.com")

        assert client._client._base_url == "https://custom.com"

    def test_has_schemas_resource(self):
        client = Unauthenticated()

        assert hasattr(client, "schemas")
        assert hasattr(client.schemas, "list")
        assert hasattr(client.schemas, "get")

