"""aho_sdk SDK for Python."""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from typing import Optional, Any

from .version import VERSION
from .exceptions import (
    ApiError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    ForbiddenError,
    NetworkError,
    NotFoundError,
    RateLimitError,
    ServerError,
    ValidationError,
)
from .page import Page
from . import types
from . import models

# Sync clients

from .account import Account

from .system import System

from .holder import Holder

from .verifier import Verifier

from .issuer import Issuer

from .schemas import Schemas

from .unauthenticated import Unauthenticated

# Async clients (requires httpx: pip install aho-sdk[async])
try:
    from .async_page import AsyncPage

    from .async_account import AsyncAccount

    from .async_system import AsyncSystem

    from .async_holder import AsyncHolder

    from .async_verifier import AsyncVerifier

    from .async_issuer import AsyncIssuer

    from .async_schemas import AsyncSchemas

    from .async_unauthenticated import AsyncUnauthenticated

    _async_available = True
except ImportError:
    _async_available = False

__version__ = VERSION

# Convenience functions

def account(api_key: str, base_url: str = "https://api.aho.com", timeout: int = 30, logger: Any = None) -> Account:
    """Create a new Account client."""
    return Account(api_key=api_key, base_url=base_url, timeout=timeout, logger=logger)

def system(api_key: str, base_url: str = "https://api.aho.com", timeout: int = 30, logger: Any = None) -> System:
    """Create a new System client."""
    return System(api_key=api_key, base_url=base_url, timeout=timeout, logger=logger)

def holder(api_key: str, base_url: str = "https://api.aho.com", timeout: int = 30, logger: Any = None) -> Holder:
    """Create a new Holder client."""
    return Holder(api_key=api_key, base_url=base_url, timeout=timeout, logger=logger)

def verifier(api_key: str, base_url: str = "https://api.aho.com", timeout: int = 30, logger: Any = None) -> Verifier:
    """Create a new Verifier client."""
    return Verifier(api_key=api_key, base_url=base_url, timeout=timeout, logger=logger)

def issuer(api_key: str, base_url: str = "https://api.aho.com", timeout: int = 30, logger: Any = None) -> Issuer:
    """Create a new Issuer client."""
    return Issuer(api_key=api_key, base_url=base_url, timeout=timeout, logger=logger)

def schemas(api_key: str, base_url: str = "https://api.aho.com", timeout: int = 30, logger: Any = None) -> Schemas:
    """Create a new Schemas client."""
    return Schemas(api_key=api_key, base_url=base_url, timeout=timeout, logger=logger)

def unauthenticated(base_url: str = "https://api.aho.com", timeout: int = 30, logger: Any = None) -> Unauthenticated:
    """Create a new Unauthenticated client."""
    return Unauthenticated(base_url=base_url, timeout=timeout, logger=logger)

__all__ = [
    "VERSION",
    # Types and models
    "types",
    "models",
    # Exceptions
    "ApiError",
    "AuthenticationError",
    "BadRequestError",
    "ConflictError",
    "ForbiddenError",
    "NetworkError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    "ValidationError",
    # Pagination
    "Page",
    # Sync clients

    "Account",

    "System",

    "Holder",

    "Verifier",

    "Issuer",

    "Schemas",

    "Unauthenticated",

    # Convenience functions

    "account",

    "system",

    "holder",

    "verifier",

    "issuer",

    "schemas",

    "unauthenticated",

]

# Add async exports if available
if _async_available:
    __all__.extend([
        "AsyncPage",

        "AsyncAccount",

        "AsyncSystem",

        "AsyncHolder",

        "AsyncVerifier",

        "AsyncIssuer",

        "AsyncSchemas",

        "AsyncUnauthenticated",

    ])
