"""Manage account settings, domains, and API keys"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .http_client import HttpClient
from .page import Page
from .cursor_page import CursorPage
from . import types as Types
from . import models as Models

class Account:
    """Manage account settings, domains, and API keys

    Example:
        client = Account(api_key=os.environ["AHO_ACCOUNT_API_KEY"])
        client.api_keys.list()
        client.regenerate.list()
        client.domains.list()
        client.signing_keys.list()
        client.webhooks.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: int = 30,
        logger: Any = None,
    ):
        """Initialize the client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
        """
        self._client = HttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
        )
        self._api_keys = _ApiKeysResource(self._client)
        self._regenerate = _RegenerateResource(self._client)
        self._domains = _DomainsResource(self._client)
        self._signing_keys = _SigningKeysResource(self._client)
        self._webhooks = _WebhooksResource(self._client)

    @property
    def api_keys(self) -> "_ApiKeysResource":
        """Api_keys resource."""
        return self._api_keys

    @property
    def regenerate(self) -> "_RegenerateResource":
        """Regenerate resource."""
        return self._regenerate

    @property
    def domains(self) -> "_DomainsResource":
        """Domains resource."""
        return self._domains

    @property
    def signing_keys(self) -> "_SigningKeysResource":
        """Signing_keys resource."""
        return self._signing_keys

    @property
    def webhooks(self) -> "_WebhooksResource":
        """Webhooks resource."""
        return self._webhooks

class _ApiKeysResource:
    """Api_keys resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def list(self) -> Optional[Models.Apikey]:
        """List API keys"""
        return self._client.get(f"/v1/account/api_keys", model_class=Models.Apikey)

    def get(self, hashid: str) -> Optional[Models.Apikey]:
        """Get API key details"""
        return self._client.get(f"/v1/account/api_keys/{hashid}", model_class=Models.Apikey)

    def update(self, hashid: str, body: Types.Updateapikeyparams, idempotency_key: Optional[str] = None) -> Optional[Models.Apikeyupdateresponse]:
        """Update API key"""
        return self._client.patch(f"/v1/account/api_keys/{hashid}", body=body, idempotency_key=idempotency_key, model_class=Models.Apikeyupdateresponse)

class _RegenerateResource:
    """Regenerate resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, hashid: str, idempotency_key: Optional[str] = None) -> Optional[Models.Apikeyregenerationresponse]:
        """Regenerate API key"""
        return self._client.post(f"/v1/account/api_keys/{hashid}/regenerate", idempotency_key=idempotency_key, model_class=Models.Apikeyregenerationresponse)

class _DomainsResource:
    """Domains resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Createdomainparams] = None, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Register a domain"""
        return self._client.post(f"/v1/account/domains", body=body, idempotency_key=idempotency_key, model_class=None)

    def list(self, txt_status: Optional[str] = None, fully_verified: Optional[str] = None, primary: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Accountdomain]:
        """List domains"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/account/domains", params={"txt_status": txt_status, "fully_verified": fully_verified, "primary": primary, "page": p, "per_page": per_page}, model_class=Models.Accountdomain)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, id: str) -> Optional[dict]:
        """Get domain details"""
        return self._client.get(f"/v1/account/domains/{id}", model_class=None)

    def delete(self, id: str) -> Optional[dict]:
        """Delete a domain"""
        return self._client.delete(f"/v1/account/domains/{id}", model_class=None)

    def verify(self, id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Domainverificationresult]:
        """Verify domain"""
        return self._client.post(f"/v1/account/domains/{id}/verify", idempotency_key=idempotency_key, model_class=Models.Domainverificationresult)

class _SigningKeysResource:
    """Signing_keys resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Createsigningkeyparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Signingkeydetails]:
        """Generate a signing key"""
        return self._client.post(f"/v1/account/signing_keys", body=body, idempotency_key=idempotency_key, model_class=Models.Signingkeydetails)

    def list(self, status: Optional[str] = None, algorithm: Optional[str] = None, usable: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Signingkey]:
        """List signing keys"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/account/signing_keys", params={"status": status, "algorithm": algorithm, "usable": usable, "page": p, "per_page": per_page}, model_class=Models.Signingkey)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, id: str) -> Optional[Models.Signingkeydetails]:
        """Get signing key details"""
        return self._client.get(f"/v1/account/signing_keys/{id}", model_class=Models.Signingkeydetails)

    def rotate(self, id: str, body: Optional[Types.Rotatesigningkeyparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Keyrotationresult]:
        """Rotate a signing key"""
        return self._client.post(f"/v1/account/signing_keys/{id}/rotate", body=body, idempotency_key=idempotency_key, model_class=Models.Keyrotationresult)

    def revoke(self, id: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Revoke a signing key"""
        return self._client.post(f"/v1/account/signing_keys/{id}/revoke", idempotency_key=idempotency_key, model_class=None)

    def certificate(self, id: str, domain: Optional[str] = None) -> Optional[Models.Certificateresponse]:
        """Download X.509 certificate"""
        return self._client.get(f"/v1/account/signing_keys/{id}/certificate", params={"domain": domain}, model_class=Models.Certificateresponse)

class _WebhooksResource:
    """Webhooks resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def list(self) -> Optional[Models.Webhook]:
        """List webhooks"""
        return self._client.get(f"/v1/account/webhooks", model_class=Models.Webhook)

    def create(self, body: Optional[Types.Createwebhookparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Webhook]:
        """Create webhook"""
        return self._client.post(f"/v1/account/webhooks", body=body, idempotency_key=idempotency_key, model_class=Models.Webhook)

    def get(self) -> Optional[Models.Webhook]:
        """Get webhook details"""
        return self._client.get(f"/v1/account/webhooks/primary", model_class=Models.Webhook)

    def update(self, body: Optional[Types.Updatewebhookparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Webhook]:
        """Update webhook"""
        return self._client.patch(f"/v1/account/webhooks/primary", body=body, idempotency_key=idempotency_key, model_class=Models.Webhook)

    def delete(self) -> Optional[dict]:
        """Delete webhook"""
        return self._client.delete(f"/v1/account/webhooks/primary", model_class=None)

    def test(self, idempotency_key: Optional[str] = None) -> Optional[Models.Webhooktestresult]:
        """Test webhook"""
        return self._client.post(f"/v1/account/webhooks/primary/test", idempotency_key=idempotency_key, model_class=Models.Webhooktestresult)

