"""Public endpoints (no authentication required) (Async)"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .async_http_client import AsyncHttpClient
from .async_page import AsyncPage
from . import types as Types
from . import models as Models

class AsyncUnauthenticated:
    """Public endpoints (no authentication required) (Async version)

    Example:
        async with AsyncUnauthenticated() as client:
            await client.schemas.list()
    """

    def __init__(
        self,
        base_url: str = "https://api.aho.com",
        timeout: float = 30.0,
        logger: Any = None,
        validate: bool = False,
    ):
        """Initialize the async client.

        Args:
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
            validate: Enable runtime validation using Pydantic models.
        """
        self._client = AsyncHttpClient(
            api_key=None,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
            validate=validate,
        )
        self._schemas = _AsyncSchemasResource(self._client)

    async def close(self) -> None:
        """Close the HTTP client."""
        await self._client.close()

    async def __aenter__(self) -> "AsyncUnauthenticated":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.close()

    @property
    def schemas(self) -> "_AsyncSchemasResource":
        """Schemas resource."""
        return self._schemas

class _AsyncSchemasResource:
    """Schemas resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def list(self, category: Optional[str] = None, tag: Optional[str] = None, q: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Credentialschema]:
        """Browse public credential schemas"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/schemas", params={"category": category, "tag": tag, "q": q, "page": p, "per_page": per_page}, model_class=Models.Credentialschema)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, slug: str) -> Page[Models.Credentialschema]:
        """Get schema details"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/schemas/{slug}", model_class=Models.Credentialschema)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(1)

