"""Async HTTP client with retry logic, credential redaction, and error handling."""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

import json
from typing import Any, Optional, Type, TypeVar

try:
    import httpx
except ImportError:
    raise ImportError(
        "httpx is required for async support. Install with: pip install aho-sdk[async]"
    )

from .exceptions import (
    ApiError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    ForbiddenError,
    NetworkError,
    NotFoundError,
    RateLimitError,
    ServerError,
    ValidationError,
)
from .version import VERSION

# Type variable for Pydantic models
T = TypeVar("T")

class AsyncHttpClient:
    """Async HTTP client with retry logic and error handling."""

    DEFAULT_TIMEOUT = 30.0  # seconds
    DEFAULT_MAX_RETRIES = 3
    DEFAULT_RETRY_DELAY = 1.0  # seconds

    # Only retry idempotent methods to prevent duplicate operations
    IDEMPOTENT_METHODS = frozenset(["GET", "DELETE", "PUT", "HEAD", "OPTIONS"])

    def __init__(
        self,
        api_key: Optional[str],
        base_url: str = "https://api.aho.com",
        timeout: float = DEFAULT_TIMEOUT,
        max_retries: int = DEFAULT_MAX_RETRIES,
        retry_delay: float = DEFAULT_RETRY_DELAY,
        logger: Any = None,
        validate: bool = False,
    ):
        """Initialize the async HTTP client.

        Args:
            api_key: API key for authentication (None for public endpoints)
            base_url: Base URL for the API
            timeout: Request timeout in seconds
            max_retries: Maximum number of retries on rate limit (default: 3)
            retry_delay: Base delay in seconds for exponential backoff (default: 1.0)
            logger: Optional logger instance
            validate: Enable runtime validation using Pydantic models
        """
        self._api_key = api_key
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout
        self._max_retries = max_retries
        self._retry_delay = retry_delay
        self._logger = logger
        self._validate = validate
        self._client: Optional[httpx.AsyncClient] = None

    async def _get_client(self) -> httpx.AsyncClient:
        """Get or create the httpx client."""
        if self._client is None or self._client.is_closed:
            self._client = httpx.AsyncClient(
                timeout=self._timeout,
                headers=self._build_headers(),
            )
        return self._client

    async def close(self) -> None:
        """Close the HTTP client."""
        if self._client is not None and not self._client.is_closed:
            await self._client.aclose()
            self._client = None

    async def __aenter__(self) -> "AsyncHttpClient":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.close()

    async def get(self, path: str, params: Optional[dict] = None, model_class: Optional[Type[T]] = None) -> Any:
        """Make a GET request."""
        return await self._request("GET", path, params=params, model_class=model_class)

    async def post(self, path: str, body: Optional[dict] = None, params: Optional[dict] = None, model_class: Optional[Type[T]] = None) -> Any:
        """Make a POST request."""
        return await self._request("POST", path, body=body, params=params, model_class=model_class)

    async def patch(self, path: str, body: Optional[dict] = None, params: Optional[dict] = None, model_class: Optional[Type[T]] = None) -> Any:
        """Make a PATCH request."""
        return await self._request("PATCH", path, body=body, params=params, model_class=model_class)

    async def put(self, path: str, body: Optional[dict] = None, params: Optional[dict] = None, model_class: Optional[Type[T]] = None) -> Any:
        """Make a PUT request."""
        return await self._request("PUT", path, body=body, params=params, model_class=model_class)

    async def delete(self, path: str, params: Optional[dict] = None, model_class: Optional[Type[T]] = None) -> Any:
        """Make a DELETE request."""
        return await self._request("DELETE", path, params=params, model_class=model_class)

    async def _request(
        self,
        method: str,
        path: str,
        body: Optional[dict] = None,
        params: Optional[dict] = None,
        model_class: Optional[Type[T]] = None,
    ) -> Any:
        """Execute an HTTP request with retry logic for idempotent methods."""
        url = self._build_url(path)
        query_params = self._build_params(params)

        self._log_request(method, url)

        retries = 0
        while True:
            try:
                return await self._execute_request(method, url, query_params, body, model_class)
            except RateLimitError as e:
                if method not in self.IDEMPOTENT_METHODS or retries >= self._max_retries:
                    raise

                retries += 1
                delay = e.retry_after if e.retry_after else self._retry_delay * (2 ** (retries - 1))
                self._log_retry(method, url, retries, delay)
                import asyncio
                await asyncio.sleep(delay)

    async def _execute_request(
        self,
        method: str,
        url: str,
        params: Optional[dict],
        body: Optional[dict],
        model_class: Optional[Type[T]] = None,
    ) -> Any:
        """Execute a single HTTP request."""
        client = await self._get_client()

        try:
            response = await client.request(
                method=method,
                url=url,
                params=params,
                json=body,
            )
            return self._handle_response(response, model_class)
        except httpx.TimeoutException:
            raise NetworkError("Request timed out")
        except httpx.RequestError as e:
            raise NetworkError(str(e))

    def _build_url(self, path: str) -> str:
        """Build the full URL."""
        return f"{self._base_url}{path}"

    def _build_params(self, params: Optional[dict]) -> Optional[dict]:
        """Build query parameters, filtering None values."""
        if not params:
            return None

        result = {}
        for key, value in params.items():
            if value is None:
                continue
            if isinstance(value, list):
                # httpx handles list params differently
                result[key] = value
            else:
                result[key] = value
        return result if result else None

    def _build_headers(self) -> dict:
        """Build request headers."""
        import sys

        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "User-Agent": f"aho_sdk/{VERSION} python/{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}",
        }
        if self._api_key:
            headers["X-API-Key"] = self._api_key
        return headers

    def _log_request(self, method: str, url: str) -> None:
        """Log request with credentials redacted."""
        if self._logger:
            self._logger.debug(f"[aho_sdk] {method} {url}")

    def _log_retry(self, method: str, url: str, attempt: int, delay: float) -> None:
        """Log retry attempt."""
        if self._logger:
            self._logger.warning(
                f"[aho_sdk] Retry {attempt}/{self._max_retries} for {method} {url} after {delay}s"
            )

    def _handle_response(self, response: httpx.Response, model_class: Optional[Type[T]] = None) -> Any:
        """Handle response and raise appropriate exceptions."""
        if response.is_success:
            if not response.content:
                return None

            data = response.json()

            # Parse response into Pydantic model if model_class provided
            if model_class is not None:
                try:
                    from pydantic import ValidationError as PydanticValidationError

                    return model_class.model_validate(data)
                except PydanticValidationError as e:
                    if self._logger:
                        self._logger.warning(f"[aho_sdk] Response validation failed: {e}")
                    return data
                except ImportError:
                    if self._logger:
                        self._logger.warning("[aho_sdk] Pydantic not installed, returning raw dict")
                    return data

            return data

        # Handle errors
        body = response.text
        status = response.status_code
        request_id = response.headers.get("X-Request-Id")
        retry_after = response.headers.get("Retry-After")

        error_classes = {
            400: BadRequestError,
            401: AuthenticationError,
            403: ForbiddenError,
            404: NotFoundError,
            409: ConflictError,
            422: ValidationError,
            429: RateLimitError,
        }

        if status in error_classes:
            exc_class = error_classes[status]
            if status == 429:
                raise exc_class(body, status, request_id, float(retry_after) if retry_after else None)
            raise exc_class(body, status, request_id)
        elif 500 <= status < 600:
            raise ServerError(body, status, request_id)
        else:
            raise ApiError(body, status, request_id)
