"""Manage account settings, domains, and API keys (Async)"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .async_http_client import AsyncHttpClient
from .async_page import AsyncPage
from . import types as Types
from . import models as Models

class AsyncAccount:
    """Manage account settings, domains, and API keys (Async version)

    Example:
        async with AsyncAccount(api_key=os.environ["AHO_ACCOUNT_API_KEY"]) as client:
            await client.api_keys.list()
            await client.regenerate.list()
            await client.domains.list()
            await client.signing_keys.list()
            await client.webhooks.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: float = 30.0,
        logger: Any = None,
        validate: bool = False,
    ):
        """Initialize the async client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
            validate: Enable runtime validation using Pydantic models.
        """
        self._client = AsyncHttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
            validate=validate,
        )
        self._api_keys = _AsyncApiKeysResource(self._client)
        self._regenerate = _AsyncRegenerateResource(self._client)
        self._domains = _AsyncDomainsResource(self._client)
        self._signing_keys = _AsyncSigningKeysResource(self._client)
        self._webhooks = _AsyncWebhooksResource(self._client)

    async def close(self) -> None:
        """Close the HTTP client."""
        await self._client.close()

    async def __aenter__(self) -> "AsyncAccount":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.close()

    @property
    def api_keys(self) -> "_AsyncApiKeysResource":
        """Api_keys resource."""
        return self._api_keys

    @property
    def regenerate(self) -> "_AsyncRegenerateResource":
        """Regenerate resource."""
        return self._regenerate

    @property
    def domains(self) -> "_AsyncDomainsResource":
        """Domains resource."""
        return self._domains

    @property
    def signing_keys(self) -> "_AsyncSigningKeysResource":
        """Signing_keys resource."""
        return self._signing_keys

    @property
    def webhooks(self) -> "_AsyncWebhooksResource":
        """Webhooks resource."""
        return self._webhooks

class _AsyncApiKeysResource:
    """Api_keys resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def list(self) -> Optional[Models.Apikey]:
        """List API keys"""
        return await self._client.get(f"/v1/account/api_keys", model_class=Models.Apikey)

    async def get(self, hashid: str) -> Optional[Models.Apikey]:
        """Get API key details"""
        return await self._client.get(f"/v1/account/api_keys/{hashid}", model_class=Models.Apikey)

    async def update(self, hashid: str, body: Types.Updateapikeyparams, idempotency_key: Optional[str] = None) -> Optional[Models.Apikeyupdateresponse]:
        """Update API key"""
        return await self._client.patch(f"/v1/account/api_keys/{hashid}", body=body, idempotency_key=idempotency_key, model_class=Models.Apikeyupdateresponse)

class _AsyncRegenerateResource:
    """Regenerate resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, hashid: str, idempotency_key: Optional[str] = None) -> Optional[Models.Apikeyregenerationresponse]:
        """Regenerate API key"""
        return await self._client.post(f"/v1/account/api_keys/{hashid}/regenerate", idempotency_key=idempotency_key, model_class=Models.Apikeyregenerationresponse)

class _AsyncDomainsResource:
    """Domains resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Createdomainparams] = None, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Register a domain"""
        return await self._client.post(f"/v1/account/domains", body=body, idempotency_key=idempotency_key, model_class=None)

    async def list(self, txt_status: Optional[str] = None, fully_verified: Optional[str] = None, primary: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Accountdomain]:
        """List domains"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/account/domains", params={"txt_status": txt_status, "fully_verified": fully_verified, "primary": primary, "page": p, "per_page": per_page}, model_class=Models.Accountdomain)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, id: str) -> Optional[dict]:
        """Get domain details"""
        return await self._client.get(f"/v1/account/domains/{id}", model_class=None)

    async def delete(self, id: str) -> Optional[dict]:
        """Delete a domain"""
        return await self._client.delete(f"/v1/account/domains/{id}", model_class=None)

    async def verify(self, id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Domainverificationresult]:
        """Verify domain"""
        return await self._client.post(f"/v1/account/domains/{id}/verify", idempotency_key=idempotency_key, model_class=Models.Domainverificationresult)

class _AsyncSigningKeysResource:
    """Signing_keys resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Createsigningkeyparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Signingkeydetails]:
        """Generate a signing key"""
        return await self._client.post(f"/v1/account/signing_keys", body=body, idempotency_key=idempotency_key, model_class=Models.Signingkeydetails)

    async def list(self, status: Optional[str] = None, algorithm: Optional[str] = None, usable: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Signingkey]:
        """List signing keys"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/account/signing_keys", params={"status": status, "algorithm": algorithm, "usable": usable, "page": p, "per_page": per_page}, model_class=Models.Signingkey)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, id: str) -> Optional[Models.Signingkeydetails]:
        """Get signing key details"""
        return await self._client.get(f"/v1/account/signing_keys/{id}", model_class=Models.Signingkeydetails)

    async def rotate(self, id: str, body: Optional[Types.Rotatesigningkeyparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Keyrotationresult]:
        """Rotate a signing key"""
        return await self._client.post(f"/v1/account/signing_keys/{id}/rotate", body=body, idempotency_key=idempotency_key, model_class=Models.Keyrotationresult)

    async def revoke(self, id: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Revoke a signing key"""
        return await self._client.post(f"/v1/account/signing_keys/{id}/revoke", idempotency_key=idempotency_key, model_class=None)

    async def certificate(self, id: str, domain: Optional[str] = None) -> Optional[Models.Certificateresponse]:
        """Download X.509 certificate"""
        return await self._client.get(f"/v1/account/signing_keys/{id}/certificate", params={"domain": domain}, model_class=Models.Certificateresponse)

class _AsyncWebhooksResource:
    """Webhooks resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def list(self) -> Optional[Models.Webhook]:
        """List webhooks"""
        return await self._client.get(f"/v1/account/webhooks", model_class=Models.Webhook)

    async def create(self, body: Optional[Types.Createwebhookparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Webhook]:
        """Create webhook"""
        return await self._client.post(f"/v1/account/webhooks", body=body, idempotency_key=idempotency_key, model_class=Models.Webhook)

    async def get(self) -> Optional[Models.Webhook]:
        """Get webhook details"""
        return await self._client.get(f"/v1/account/webhooks/primary", model_class=Models.Webhook)

    async def update(self, body: Optional[Types.Updatewebhookparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Webhook]:
        """Update webhook"""
        return await self._client.patch(f"/v1/account/webhooks/primary", body=body, idempotency_key=idempotency_key, model_class=Models.Webhook)

    async def delete(self) -> Optional[dict]:
        """Delete webhook"""
        return await self._client.delete(f"/v1/account/webhooks/primary", model_class=None)

    async def test(self, idempotency_key: Optional[str] = None) -> Optional[Models.Webhooktestresult]:
        """Test webhook"""
        return await self._client.post(f"/v1/account/webhooks/primary/test", idempotency_key=idempotency_key, model_class=Models.Webhooktestresult)

