"""Issue and manage verifiable credentials (Async)"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .async_http_client import AsyncHttpClient
from .async_page import AsyncPage
from . import types as Types
from . import models as Models

class AsyncIssuer:
    """Issue and manage verifiable credentials (Async version)

    Example:
        async with AsyncIssuer(api_key=os.environ["AHO_ISSUER_API_KEY"]) as client:
            await client.automations.list()
            await client.credentials.list()
            await client.revoke_batch.list()
            await client.suspend_batch.list()
            await client.reinstate_batch.list()
            await client.data_source_mappings.list()
            await client.data_sources.list()
            await client.offers.list()
            await client.schemas.list()
            await client.verify.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: float = 30.0,
        logger: Any = None,
        validate: bool = False,
    ):
        """Initialize the async client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
            validate: Enable runtime validation using Pydantic models.
        """
        self._client = AsyncHttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
            validate=validate,
        )
        self._automations = _AsyncAutomationsResource(self._client)
        self._credentials = _AsyncCredentialsResource(self._client)
        self._revoke_batch = _AsyncRevokeBatchResource(self._client)
        self._suspend_batch = _AsyncSuspendBatchResource(self._client)
        self._reinstate_batch = _AsyncReinstateBatchResource(self._client)
        self._data_source_mappings = _AsyncDataSourceMappingsResource(self._client)
        self._data_sources = _AsyncDataSourcesResource(self._client)
        self._offers = _AsyncOffersResource(self._client)
        self._schemas = _AsyncSchemasResource(self._client)
        self._verify = _AsyncVerifyResource(self._client)

    async def close(self) -> None:
        """Close the HTTP client."""
        await self._client.close()

    async def __aenter__(self) -> "AsyncIssuer":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.close()

    @property
    def automations(self) -> "_AsyncAutomationsResource":
        """Automations resource."""
        return self._automations

    @property
    def credentials(self) -> "_AsyncCredentialsResource":
        """Credentials resource."""
        return self._credentials

    @property
    def revoke_batch(self) -> "_AsyncRevokeBatchResource":
        """Revoke_batch resource."""
        return self._revoke_batch

    @property
    def suspend_batch(self) -> "_AsyncSuspendBatchResource":
        """Suspend_batch resource."""
        return self._suspend_batch

    @property
    def reinstate_batch(self) -> "_AsyncReinstateBatchResource":
        """Reinstate_batch resource."""
        return self._reinstate_batch

    @property
    def data_source_mappings(self) -> "_AsyncDataSourceMappingsResource":
        """Data_source_mappings resource."""
        return self._data_source_mappings

    @property
    def data_sources(self) -> "_AsyncDataSourcesResource":
        """Data_sources resource."""
        return self._data_sources

    @property
    def offers(self) -> "_AsyncOffersResource":
        """Offers resource."""
        return self._offers

    @property
    def schemas(self) -> "_AsyncSchemasResource":
        """Schemas resource."""
        return self._schemas

    @property
    def verify(self) -> "_AsyncVerifyResource":
        """Verify resource."""
        return self._verify

class _AsyncAutomationsResource:
    """Automations resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def get_webhook(self, automation_id: str) -> Optional[Models.Automationwebhook]:
        """Get webhook configuration"""
        return await self._client.get(f"/v1/issuer/automations/{automation_id}/webhook", model_class=Models.Automationwebhook)

    async def create_webhook(self, automation_id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Automationwebhook]:
        """Generate webhook token"""
        return await self._client.post(f"/v1/issuer/automations/{automation_id}/webhook", idempotency_key=idempotency_key, model_class=Models.Automationwebhook)

    async def delete_webhook(self, automation_id: str) -> Optional[dict]:
        """Revoke webhook token"""
        return await self._client.delete(f"/v1/issuer/automations/{automation_id}/webhook", model_class=None)

    async def create(self, body: Optional[Types.Createautomationparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialautomation]:
        """Create an automation"""
        return await self._client.post(f"/v1/issuer/automations", body=body, idempotency_key=idempotency_key, model_class=Models.Credentialautomation)

    async def list(self, status: Optional[str] = None, trigger_mode: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Credentialautomation]:
        """List automations"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/issuer/automations", params={"status": status, "trigger_mode": trigger_mode, "page": p, "per_page": per_page}, model_class=Models.Credentialautomation)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, id: str) -> Optional[Models.Credentialautomation]:
        """Get automation details"""
        return await self._client.get(f"/v1/issuer/automations/{id}", model_class=Models.Credentialautomation)

    async def update(self, id: str, body: Optional[Types.Updateautomationparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialautomation]:
        """Update an automation"""
        return await self._client.patch(f"/v1/issuer/automations/{id}", body=body, idempotency_key=idempotency_key, model_class=Models.Credentialautomation)

    async def delete(self, id: str) -> Optional[dict]:
        """Delete an automation"""
        return await self._client.delete(f"/v1/issuer/automations/{id}", model_class=None)

    async def trigger(self, id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Automationtriggerresult]:
        """Trigger an automation"""
        return await self._client.post(f"/v1/issuer/automations/{id}/trigger", idempotency_key=idempotency_key, model_class=Models.Automationtriggerresult)

    async def pause(self, id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialautomation]:
        """Pause an automation"""
        return await self._client.post(f"/v1/issuer/automations/{id}/pause", idempotency_key=idempotency_key, model_class=Models.Credentialautomation)

    async def resume(self, id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialautomation]:
        """Resume an automation"""
        return await self._client.post(f"/v1/issuer/automations/{id}/resume", idempotency_key=idempotency_key, model_class=Models.Credentialautomation)

class _AsyncCredentialsResource:
    """Credentials resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Createcredentialparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialissuance]:
        """Issue a new credential"""
        return await self._client.post(f"/v1/issuer/credentials", body=body, idempotency_key=idempotency_key, model_class=Models.Credentialissuance)

    async def list(self, status: Optional[str] = None, schema: Optional[str] = None, subject_identifier: Optional[str] = None, issued_after: Optional[str] = None, issued_before: Optional[str] = None, expires_after: Optional[str] = None, expires_before: Optional[str] = None, sort: Optional[str] = "issued_at", direction: Optional[str] = "desc", page: Optional[int] = 1, per_page: Optional[int] = 25) -> Page[Models.Credentialissuance]:
        """List credentials"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/issuer/credentials", params={"status": status, "schema": schema, "subject_identifier": subject_identifier, "issued_after": issued_after, "issued_before": issued_before, "expires_after": expires_after, "expires_before": expires_before, "sort": sort, "direction": direction, "page": p, "per_page": per_page}, model_class=Models.Credentialissuance)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, uuid: str) -> Optional[Models.Credentialissuance]:
        """Get issued credential details"""
        return await self._client.get(f"/v1/issuer/credentials/{uuid}", model_class=Models.Credentialissuance)

    async def revoke(self, uuid: str, body: Optional[Types.Revokecredentialparams] = None, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Revoke a credential"""
        return await self._client.post(f"/v1/issuer/credentials/{uuid}/revoke", body=body, idempotency_key=idempotency_key, model_class=None)

    async def suspend(self, uuid: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Suspend a credential"""
        return await self._client.post(f"/v1/issuer/credentials/{uuid}/suspend", idempotency_key=idempotency_key, model_class=None)

    async def reinstate(self, uuid: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Reinstate a suspended credential"""
        return await self._client.post(f"/v1/issuer/credentials/{uuid}/reinstate", idempotency_key=idempotency_key, model_class=None)

    async def status(self, uuid: str) -> Optional[dict]:
        """Get credential status"""
        return await self._client.get(f"/v1/issuer/credentials/{uuid}/status", model_class=None)

    async def history(self, uuid: str) -> Optional[dict]:
        """Get credential history"""
        return await self._client.get(f"/v1/issuer/credentials/{uuid}/history", model_class=None)

class _AsyncRevokeBatchResource:
    """Revoke_batch resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Revokebatchparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Batchoperationresult]:
        """Revoke multiple credentials"""
        return await self._client.post(f"/v1/issuer/credentials/revoke_batch", body=body, idempotency_key=idempotency_key, model_class=Models.Batchoperationresult)

class _AsyncSuspendBatchResource:
    """Suspend_batch resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Suspendbatchparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Batchoperationresult]:
        """Suspend multiple credentials"""
        return await self._client.post(f"/v1/issuer/credentials/suspend_batch", body=body, idempotency_key=idempotency_key, model_class=Models.Batchoperationresult)

class _AsyncReinstateBatchResource:
    """Reinstate_batch resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Reinstatebatchparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Batchoperationresult]:
        """Reinstate multiple credentials"""
        return await self._client.post(f"/v1/issuer/credentials/reinstate_batch", body=body, idempotency_key=idempotency_key, model_class=Models.Batchoperationresult)

class _AsyncDataSourceMappingsResource:
    """Data_source_mappings resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Createdatasourcemappingparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Datasourcemapping]:
        """Create a data source mapping"""
        return await self._client.post(f"/v1/issuer/data_source_mappings", body=body, idempotency_key=idempotency_key, model_class=Models.Datasourcemapping)

    async def list(self, data_source: Optional[str] = None, credential_schema: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Datasourcemapping]:
        """List data source mappings"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/issuer/data_source_mappings", params={"data_source": data_source, "credential_schema": credential_schema, "page": p, "per_page": per_page}, model_class=Models.Datasourcemapping)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, id: str) -> Optional[Models.Datasourcemapping]:
        """Get mapping details"""
        return await self._client.get(f"/v1/issuer/data_source_mappings/{id}", model_class=Models.Datasourcemapping)

    async def update(self, id: str, body: Optional[Types.Updatedatasourcemappingparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Datasourcemapping]:
        """Update a mapping"""
        return await self._client.patch(f"/v1/issuer/data_source_mappings/{id}", body=body, idempotency_key=idempotency_key, model_class=Models.Datasourcemapping)

    async def delete(self, id: str) -> Optional[dict]:
        """Delete a mapping"""
        return await self._client.delete(f"/v1/issuer/data_source_mappings/{id}", model_class=None)

class _AsyncDataSourcesResource:
    """Data_sources resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Createdatasourceparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Datasource]:
        """Create a data source"""
        return await self._client.post(f"/v1/issuer/data_sources", body=body, idempotency_key=idempotency_key, model_class=Models.Datasource)

    async def list(self, status: Optional[str] = None, source_type: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Datasource]:
        """List data sources"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/issuer/data_sources", params={"status": status, "source_type": source_type, "page": p, "per_page": per_page}, model_class=Models.Datasource)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, id: str) -> Optional[Models.Datasource]:
        """Get data source details"""
        return await self._client.get(f"/v1/issuer/data_sources/{id}", model_class=Models.Datasource)

    async def update(self, id: str, body: Optional[Types.Updatedatasourceparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Datasource]:
        """Update a data source"""
        return await self._client.patch(f"/v1/issuer/data_sources/{id}", body=body, idempotency_key=idempotency_key, model_class=Models.Datasource)

    async def delete(self, id: str) -> Optional[dict]:
        """Delete a data source"""
        return await self._client.delete(f"/v1/issuer/data_sources/{id}", model_class=None)

    async def test(self, id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Datasourcetestresult]:
        """Test data source connection"""
        return await self._client.post(f"/v1/issuer/data_sources/{id}/test", idempotency_key=idempotency_key, model_class=Models.Datasourcetestresult)

class _AsyncOffersResource:
    """Offers resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def list(self, page: Optional[int] = None, per_page: Optional[int] = None, status: Optional[str] = None, created_after: Optional[str] = None, created_before: Optional[str] = None, expires_after: Optional[str] = None, expires_before: Optional[str] = None, schema: Optional[str] = None, subject_identifier: Optional[str] = None, sort: Optional[str] = None, direction: Optional[str] = None) -> Page[Models.Credentialoffer]:
        """List credential offers"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/issuer/offers", params={"page": p, "per_page": per_page, "status": status, "created_after": created_after, "created_before": created_before, "expires_after": expires_after, "expires_before": expires_before, "schema": schema, "subject_identifier": subject_identifier, "sort": sort, "direction": direction}, model_class=Models.Credentialoffer)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def create(self, body: Optional[Types.Createofferparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialofferresult]:
        """Create a credential offer"""
        return await self._client.post(f"/v1/issuer/offers", body=body, idempotency_key=idempotency_key, model_class=Models.Credentialofferresult)

    async def get(self, uuid: str) -> Optional[Models.Credentialoffer]:
        """Get credential offer details"""
        return await self._client.get(f"/v1/issuer/offers/{uuid}", model_class=Models.Credentialoffer)

    async def revoke(self, uuid: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Revoke a credential offer"""
        return await self._client.post(f"/v1/issuer/offers/{uuid}/revoke", idempotency_key=idempotency_key, model_class=None)

class _AsyncSchemasResource:
    """Schemas resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Createschemaparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Issuercredentialschema]:
        """Create a credential schema"""
        return await self._client.post(f"/v1/issuer/schemas", body=body, idempotency_key=idempotency_key, model_class=Models.Issuercredentialschema)

    async def list(self, status: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Issuercredentialschema]:
        """List issuer credential schemas"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/issuer/schemas", params={"status": status, "page": p, "per_page": per_page}, model_class=Models.Issuercredentialschema)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, id: str) -> Optional[Models.Issuercredentialschema]:
        """Get credential schema details"""
        return await self._client.get(f"/v1/issuer/schemas/{id}", model_class=Models.Issuercredentialschema)

    async def update(self, id: str, body: Optional[Types.Updateschemaparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Issuercredentialschema]:
        """Update a draft credential schema"""
        return await self._client.patch(f"/v1/issuer/schemas/{id}", body=body, idempotency_key=idempotency_key, model_class=Models.Issuercredentialschema)

    async def delete(self, id: str) -> Optional[dict]:
        """Delete a draft credential schema"""
        return await self._client.delete(f"/v1/issuer/schemas/{id}", model_class=None)

    async def activate(self, id: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Activate a draft credential schema"""
        return await self._client.post(f"/v1/issuer/schemas/{id}/activate", idempotency_key=idempotency_key, model_class=None)

    async def archive(self, id: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Archive an active credential schema"""
        return await self._client.post(f"/v1/issuer/schemas/{id}/archive", idempotency_key=idempotency_key, model_class=None)

class _AsyncVerifyResource:
    """Verify resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def get(self, uuid: str) -> Optional[Models.Verificationresult]:
        """Verify a credential by UUID"""
        return await self._client.get(f"/v1/issuer/verify/{uuid}", model_class=Models.Verificationresult)

    async def create(self, body: Optional[Types.Verifycredentialparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Verificationresult]:
        """Verify a credential"""
        return await self._client.post(f"/v1/issuer/verify", body=body, idempotency_key=idempotency_key, model_class=Models.Verificationresult)

