"""Manage holder credentials and presentations (Async)"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .async_http_client import AsyncHttpClient
from .async_page import AsyncPage
from . import types as Types
from . import models as Models

class AsyncHolder:
    """Manage holder credentials and presentations (Async version)

    Example:
        async with AsyncHolder(api_key=os.environ["AHO_HOLDER_API_KEY"]) as client:
            await client.credentials.list()
            await client.presentations.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: float = 30.0,
        logger: Any = None,
        validate: bool = False,
    ):
        """Initialize the async client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
            validate: Enable runtime validation using Pydantic models.
        """
        self._client = AsyncHttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
            validate=validate,
        )
        self._credentials = _AsyncCredentialsResource(self._client)
        self._presentations = _AsyncPresentationsResource(self._client)

    async def close(self) -> None:
        """Close the HTTP client."""
        await self._client.close()

    async def __aenter__(self) -> "AsyncHolder":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.close()

    @property
    def credentials(self) -> "_AsyncCredentialsResource":
        """Credentials resource."""
        return self._credentials

    @property
    def presentations(self) -> "_AsyncPresentationsResource":
        """Presentations resource."""
        return self._presentations

class _AsyncCredentialsResource:
    """Credentials resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def list(self, page: Optional[int] = None, per_page: Optional[int] = None, status: Optional[str] = None, sort: Optional[str] = None, direction: Optional[str] = None) -> Page:
        """List holder credentials"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/holder/credentials", params={"page": p, "per_page": per_page, "status": status, "sort": sort, "direction": direction}, model_class=None)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, uuid: str) -> Optional[dict]:
        """Get holder credential details"""
        return await self._client.get(f"/v1/holder/credentials/{uuid}", model_class=None)

class _AsyncPresentationsResource:
    """Presentations resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def list(self, page: Optional[int] = None, per_page: Optional[int] = None, status: Optional[str] = None, credential_uuid: Optional[str] = None, sort: Optional[str] = None, direction: Optional[str] = None) -> Page[Models.Presentation]:
        """List holder presentations"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/holder/presentations", params={"page": p, "per_page": per_page, "status": status, "credential_uuid": credential_uuid, "sort": sort, "direction": direction}, model_class=Models.Presentation)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def create(self, body: Optional[Types.Createpresentationparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Presentation]:
        """Create a credential presentation"""
        return await self._client.post(f"/v1/holder/presentations", body=body, idempotency_key=idempotency_key, model_class=Models.Presentation)

    async def get(self, uuid: str) -> Optional[Models.Presentation]:
        """Get presentation details"""
        return await self._client.get(f"/v1/holder/presentations/{uuid}", model_class=Models.Presentation)

    async def delete(self, uuid: str) -> Optional[dict]:
        """Revoke a presentation"""
        return await self._client.delete(f"/v1/holder/presentations/{uuid}", model_class=None)

