"""Browse and retrieve credential schemas (Async)"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .async_http_client import AsyncHttpClient
from .async_page import AsyncPage
from . import types as Types
from . import models as Models

class AsyncSchemas:
    """Browse and retrieve credential schemas (Async version)

    Example:
        async with AsyncSchemas(api_key=os.environ["AHO_SCHEMAS_API_KEY"]) as client:
            await client.render_templates.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: float = 30.0,
        logger: Any = None,
        validate: bool = False,
    ):
        """Initialize the async client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
            validate: Enable runtime validation using Pydantic models.
        """
        self._client = AsyncHttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
            validate=validate,
        )
        self._render_templates = _AsyncRenderTemplatesResource(self._client)

    async def close(self) -> None:
        """Close the HTTP client."""
        await self._client.close()

    async def __aenter__(self) -> "AsyncSchemas":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.close()

    @property
    def render_templates(self) -> "_AsyncRenderTemplatesResource":
        """Render_templates resource."""
        return self._render_templates

class _AsyncRenderTemplatesResource:
    """Render_templates resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def list(self, schema_id: str) -> Page[Models.Rendertemplate]:
        """List render templates"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/schemas/{schema_id}/render_templates", model_class=Models.Rendertemplate)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(1)

    async def create(self, schema_id: str, body: Optional[Types.Createrendertemplateparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Rendertemplate]:
        """Create render template"""
        return await self._client.post(f"/v1/schemas/{schema_id}/render_templates", body=body, idempotency_key=idempotency_key, model_class=Models.Rendertemplate)

    async def get(self, schema_id: str, id: str) -> Optional[Models.Rendertemplate]:
        """Get render template"""
        return await self._client.get(f"/v1/schemas/{schema_id}/render_templates/{id}", model_class=Models.Rendertemplate)

    async def update(self, schema_id: str, id: str, body: Optional[Types.Updaterendertemplateparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Rendertemplate]:
        """Update render template"""
        return await self._client.patch(f"/v1/schemas/{schema_id}/render_templates/{id}", body=body, idempotency_key=idempotency_key, model_class=Models.Rendertemplate)

    async def delete(self, schema_id: str, id: str) -> Optional[dict]:
        """Delete render template"""
        return await self._client.delete(f"/v1/schemas/{schema_id}/render_templates/{id}", model_class=None)

    async def validate(self, schema_id: str, body: Optional[Types.Validaterendertemplateparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Rendertemplatevalidationresult]:
        """Validate template"""
        return await self._client.post(f"/v1/schemas/{schema_id}/render_templates/validate", body=body, idempotency_key=idempotency_key, model_class=Models.Rendertemplatevalidationresult)

