"""System health and status endpoints (Async)"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .async_http_client import AsyncHttpClient
from .async_page import AsyncPage
from . import types as Types
from . import models as Models

class AsyncSystem:
    """System health and status endpoints (Async version)

    Example:
        async with AsyncSystem(api_key=os.environ["AHO_SYSTEM_API_KEY"]) as client:
            await client.health.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: float = 30.0,
        logger: Any = None,
        validate: bool = False,
    ):
        """Initialize the async client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
            validate: Enable runtime validation using Pydantic models.
        """
        self._client = AsyncHttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
            validate=validate,
        )
        self._health = _AsyncHealthResource(self._client)

    async def close(self) -> None:
        """Close the HTTP client."""
        await self._client.close()

    async def __aenter__(self) -> "AsyncSystem":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.close()

    @property
    def health(self) -> "_AsyncHealthResource":
        """Health resource."""
        return self._health

class _AsyncHealthResource:
    """Health resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def get(self) -> Optional[dict]:
        """Health check"""
        return await self._client.get(f"/v1/health", model_class=None)

