"""Create presentation requests and verify credentials (Async)"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .async_http_client import AsyncHttpClient
from .async_page import AsyncPage
from . import types as Types
from . import models as Models

class AsyncVerifier:
    """Create presentation requests and verify credentials (Async version)

    Example:
        async with AsyncVerifier(api_key=os.environ["AHO_VERIFIER_API_KEY"]) as client:
            await client.presentations.list()
            await client.dc_sessions.list()
            await client.render.list()
            await client.requests.list()
            await client.responses.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: float = 30.0,
        logger: Any = None,
        validate: bool = False,
    ):
        """Initialize the async client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
            validate: Enable runtime validation using Pydantic models.
        """
        self._client = AsyncHttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
            validate=validate,
        )
        self._presentations = _AsyncPresentationsResource(self._client)
        self._dc_sessions = _AsyncDcSessionsResource(self._client)
        self._render = _AsyncRenderResource(self._client)
        self._requests = _AsyncRequestsResource(self._client)
        self._responses = _AsyncResponsesResource(self._client)

    async def close(self) -> None:
        """Close the HTTP client."""
        await self._client.close()

    async def __aenter__(self) -> "AsyncVerifier":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.close()

    @property
    def presentations(self) -> "_AsyncPresentationsResource":
        """Presentations resource."""
        return self._presentations

    @property
    def dc_sessions(self) -> "_AsyncDcSessionsResource":
        """Dc_sessions resource."""
        return self._dc_sessions

    @property
    def render(self) -> "_AsyncRenderResource":
        """Render resource."""
        return self._render

    @property
    def requests(self) -> "_AsyncRequestsResource":
        """Requests resource."""
        return self._requests

    @property
    def responses(self) -> "_AsyncResponsesResource":
        """Responses resource."""
        return self._responses

class _AsyncPresentationsResource:
    """Presentations resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def verify(self, body: Optional[Types.Verifypresentationparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Presentationverifyresult]:
        """Verify a presentation"""
        return await self._client.post(f"/v1/verifier/presentations/verify", body=body, idempotency_key=idempotency_key, model_class=Models.Presentationverifyresult)

class _AsyncDcSessionsResource:
    """Dc_sessions resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Createdcsessionparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Dcapisessioncreateresponse]:
        """Create a DC API session"""
        return await self._client.post(f"/v1/verifier/dc_sessions", body=body, idempotency_key=idempotency_key, model_class=Models.Dcapisessioncreateresponse)

    async def get(self, id: str) -> Optional[Models.Dcapisession]:
        """Get DC API session status"""
        return await self._client.get(f"/v1/verifier/dc_sessions/{id}", model_class=Models.Dcapisession)

    async def verify(self, id: str, body: Optional[Types.Verifydcsessionparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Dcapisessionverifyresponse]:
        """Verify a DC API session"""
        return await self._client.post(f"/v1/verifier/dc_sessions/{id}/verify", body=body, idempotency_key=idempotency_key, model_class=Models.Dcapisessionverifyresponse)

class _AsyncRenderResource:
    """Render resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def list(self, id: str, format: Optional[str] = None) -> Optional[dict]:
        """Render verified claims as visual credential"""
        return await self._client.get(f"/v1/verifier/dc_sessions/{id}/render", params={"format": format}, model_class=None)

    async def create(self, body: Optional[Types.Renderparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Renderresponse]:
        """Render claims as visual credential"""
        return await self._client.post(f"/v1/verifier/render", body=body, idempotency_key=idempotency_key, model_class=Models.Renderresponse)

class _AsyncRequestsResource:
    """Requests resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def create(self, body: Optional[Types.Createpresentationrequestparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Presentationrequest]:
        """Create a presentation request"""
        return await self._client.post(f"/v1/verifier/requests", body=body, idempotency_key=idempotency_key, model_class=Models.Presentationrequest)

    async def list(self, status: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Presentationrequest]:
        """List presentation requests"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/verifier/requests", params={"status": status, "page": p, "per_page": per_page}, model_class=Models.Presentationrequest)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, uuid: str) -> Optional[Models.Presentationrequest]:
        """Get presentation request details"""
        return await self._client.get(f"/v1/verifier/requests/{uuid}", model_class=Models.Presentationrequest)

    async def update(self, uuid: str, body: Optional[Types.Updatepresentationrequestparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Presentationrequest]:
        """Update a draft presentation request"""
        return await self._client.patch(f"/v1/verifier/requests/{uuid}", body=body, idempotency_key=idempotency_key, model_class=Models.Presentationrequest)

    async def delete(self, uuid: str) -> Optional[dict]:
        """Delete a draft presentation request"""
        return await self._client.delete(f"/v1/verifier/requests/{uuid}", model_class=None)

    async def activate(self, uuid: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Activate a draft presentation request"""
        return await self._client.post(f"/v1/verifier/requests/{uuid}/activate", idempotency_key=idempotency_key, model_class=None)

    async def close(self, uuid: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Close an active presentation request"""
        return await self._client.post(f"/v1/verifier/requests/{uuid}/close", idempotency_key=idempotency_key, model_class=None)

    async def qr_code(self, uuid: str, format: Optional[str] = None, output_format: str = "svg") -> bytes:
        """Get QR code for presentation request"""
        format_map = {{"svg": "image/svg+xml", "png": "image/png", "json": "application/json"}}
        accept = format_map.get(output_format, list(format_map.values())[0])
        return await self._client.get(f"/v1/verifier/requests/{uuid}/qr_code", params={"format": format}, accept=accept)

class _AsyncResponsesResource:
    """Responses resource operations (async)."""

    def __init__(self, client: AsyncHttpClient):
        self._client = client

    async def list(self, request_uuid: str, status: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Presentationresponse]:
        """List responses for a presentation request"""
        async def fetch_page(p: int) -> AsyncPage:
            response = await self._client.get(f"/v1/verifier/requests/{request_uuid}/responses", params={"status": status, "page": p, "per_page": per_page}, model_class=Models.Presentationresponse)
            return AsyncPage(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return await fetch_page(page)

    async def get(self, request_uuid: str, uuid: str) -> Optional[Models.Presentationresponse]:
        """Get response details"""
        return await self._client.get(f"/v1/verifier/requests/{request_uuid}/responses/{uuid}", model_class=Models.Presentationresponse)

