"""Cursor pagination support with lazy iteration."""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Callable, Iterator, Optional

class CursorPage:
    """Cursor-paginated response with lazy iteration support.

    Example:
        # Iterate through all pages
        page = issuer.credentials.list()
        for credential in page:
            print(credential["uuid"])

        # Manual pagination
        page = issuer.credentials.list()
        while page:
            for c in page.data:
                print(c["uuid"])
            page = page.next_page()
    """

    def __init__(
        self,
        data: list[dict],
        meta: dict,
        fetch_next: Callable[[str], Optional["CursorPage"]],
    ):
        """Initialize a cursor page.

        Args:
            data: Items on this page.
            meta: Pagination metadata (cursor, has_more, next_cursor).
            fetch_next: Callable to fetch the next page given a cursor.
        """
        self._data = data
        self._meta = meta
        self._fetch_next = fetch_next

    @property
    def data(self) -> list[dict]:
        """Items on this page."""
        return self._data

    @property
    def meta(self) -> dict:
        """Pagination metadata."""
        return self._meta

    @property
    def has_more(self) -> bool:
        """Check if there are more pages."""
        return self._meta.get("has_more", False)

    @property
    def next_cursor(self) -> Optional[str]:
        """Cursor for the next page."""
        return self._meta.get("next_cursor")

    @property
    def cursor(self) -> Optional[str]:
        """Cursor for the current page (if provided)."""
        return self._meta.get("cursor")

    @property
    def per_page(self) -> Optional[int]:
        """Number of items per page (if provided)."""
        return self._meta.get("per_page")

    def next_page(self) -> Optional["CursorPage"]:
        """Fetch the next page.

        Returns:
            Next page or None if this is the last page.
        """
        if not self.has_more:
            return None
        cursor = self.next_cursor
        if cursor is None:
            return None
        return self._fetch_next(cursor)

    def __iter__(self) -> Iterator[dict]:
        """Iterate through all items across all pages (lazy loading)."""
        page: Optional[CursorPage] = self
        while page is not None:
            yield from page.data
            page = page.next_page()

    def __len__(self) -> int:
        """Return number of items on this page."""
        return len(self._data)

    def __bool__(self) -> bool:
        """Return True if there are items on this page."""
        return len(self._data) > 0
