"""Exception classes for API errors."""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

import json
from typing import Any, Optional

class ApiError(Exception):
    """Base exception for API errors."""

    def __init__(
        self,
        body: str,
        status_code: int,
        request_id: Optional[str] = None,
    ):
        self.status_code = status_code
        self.request_id = request_id
        self.raw_body = body

        try:
            parsed = json.loads(body)
            error = parsed.get("error", parsed)
            self.error_code = error.get("code")
            self.details = self._normalize_details(error.get("details"))
            message = error.get("message", body)
        except (json.JSONDecodeError, AttributeError):
            self.error_code = "unknown"
            self.details = []
            message = body

        super().__init__(message)

    def _normalize_details(self, details: Any) -> list[dict]:
        """Normalize details to array of FieldError-like dicts.

        API can return: string, array of strings, array of FieldError objects,
        hash, or None.
        """
        if details is None:
            return []

        if isinstance(details, str):
            return [{"field": "_base", "issue": "error", "hint": details}]

        if isinstance(details, list):
            result = []
            for item in details:
                if isinstance(item, str):
                    result.append({"field": "_base", "issue": "error", "hint": item})
                elif isinstance(item, dict):
                    result.append(item)
                else:
                    result.append({"field": "_base", "issue": "error", "hint": str(item)})
            return result

        if isinstance(details, dict):
            # Legacy format: { field_name: [errors] }
            result = []
            for field, errors in details.items():
                if isinstance(errors, list):
                    for error in errors:
                        result.append({
                            "field": str(field),
                            "issue": "validation_failed",
                            "hint": error,
                        })
                else:
                    result.append({
                        "field": str(field),
                        "issue": "validation_failed",
                        "hint": errors,
                    })
            return result

        return [{"field": "_base", "issue": "error", "hint": str(details)}]

class BadRequestError(ApiError):
    """400 Bad Request."""
    pass

class AuthenticationError(ApiError):
    """401 Unauthorized."""
    pass

class ForbiddenError(ApiError):
    """403 Forbidden."""
    pass

class NotFoundError(ApiError):
    """404 Not Found."""
    pass

class ConflictError(ApiError):
    """409 Conflict."""
    pass

class ValidationError(ApiError):
    """422 Unprocessable Entity."""

    @property
    def field_errors(self) -> list[dict]:
        """Return normalized details as field errors."""
        return self.details or []

    @property
    def errors_by_field(self) -> dict[str, list[dict]]:
        """Group errors by field name."""
        result: dict[str, list[dict]] = {}
        for error in self.field_errors:
            field = error.get("field", "_base")
            if field not in result:
                result[field] = []
            result[field].append(error)
        return result

class RateLimitError(ApiError):
    """429 Too Many Requests."""

    def __init__(
        self,
        body: str,
        status_code: int,
        request_id: Optional[str] = None,
        retry_after: Optional[float] = None,
    ):
        super().__init__(body, status_code, request_id)
        self.retry_after = retry_after

class ServerError(ApiError):
    """5xx Server Error."""
    pass

class NetworkError(Exception):
    """Network-level error (connection refused, timeout, etc.)."""

    def __init__(self, message: str):
        super().__init__(message)
        self.status_code = 0
