"""Manage holder credentials and presentations"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .http_client import HttpClient
from .page import Page
from .cursor_page import CursorPage
from . import types as Types
from . import models as Models

class Holder:
    """Manage holder credentials and presentations

    Example:
        client = Holder(api_key=os.environ["AHO_HOLDER_API_KEY"])
        client.credentials.list()
        client.presentations.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: int = 30,
        logger: Any = None,
    ):
        """Initialize the client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
        """
        self._client = HttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
        )
        self._credentials = _CredentialsResource(self._client)
        self._presentations = _PresentationsResource(self._client)

    @property
    def credentials(self) -> "_CredentialsResource":
        """Credentials resource."""
        return self._credentials

    @property
    def presentations(self) -> "_PresentationsResource":
        """Presentations resource."""
        return self._presentations

class _CredentialsResource:
    """Credentials resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def list(self, page: Optional[int] = None, per_page: Optional[int] = None, status: Optional[str] = None, sort: Optional[str] = None, direction: Optional[str] = None) -> Page:
        """List holder credentials"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/holder/credentials", params={"page": p, "per_page": per_page, "status": status, "sort": sort, "direction": direction}, model_class=None)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, uuid: str) -> Optional[dict]:
        """Get holder credential details"""
        return self._client.get(f"/v1/holder/credentials/{uuid}", model_class=None)

class _PresentationsResource:
    """Presentations resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def list(self, page: Optional[int] = None, per_page: Optional[int] = None, status: Optional[str] = None, credential_uuid: Optional[str] = None, sort: Optional[str] = None, direction: Optional[str] = None) -> Page[Models.Presentation]:
        """List holder presentations"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/holder/presentations", params={"page": p, "per_page": per_page, "status": status, "credential_uuid": credential_uuid, "sort": sort, "direction": direction}, model_class=Models.Presentation)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def create(self, body: Optional[Types.Createpresentationparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Presentation]:
        """Create a credential presentation"""
        return self._client.post(f"/v1/holder/presentations", body=body, idempotency_key=idempotency_key, model_class=Models.Presentation)

    def get(self, uuid: str) -> Optional[Models.Presentation]:
        """Get presentation details"""
        return self._client.get(f"/v1/holder/presentations/{uuid}", model_class=Models.Presentation)

    def delete(self, uuid: str) -> Optional[dict]:
        """Revoke a presentation"""
        return self._client.delete(f"/v1/holder/presentations/{uuid}", model_class=None)

