"""HTTP client with retry logic, credential redaction, and error handling."""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

import json
import time
from typing import Any, Optional, Type, TypeVar
from urllib.parse import urlencode, urljoin
import urllib.request
import urllib.error

from .exceptions import (
    ApiError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    ForbiddenError,
    NetworkError,
    NotFoundError,
    RateLimitError,
    ServerError,
    ValidationError,
)
from .version import VERSION

# Type variable for Pydantic models
T = TypeVar("T")

class HttpClient:
    """HTTP client with retry logic and error handling."""

    DEFAULT_TIMEOUT = 30  # seconds
    DEFAULT_MAX_RETRIES = 3
    DEFAULT_RETRY_DELAY = 1.0  # seconds

    # Only retry idempotent methods to prevent duplicate operations
    IDEMPOTENT_METHODS = frozenset(["GET", "DELETE", "PUT", "HEAD", "OPTIONS"])

    def __init__(
        self,
        api_key: Optional[str],
        base_url: str = "https://api.aho.com",
        timeout: int = DEFAULT_TIMEOUT,
        max_retries: int = DEFAULT_MAX_RETRIES,
        retry_delay: float = DEFAULT_RETRY_DELAY,
        logger: Any = None,
        validate: bool = False,
    ):
        """Initialize the HTTP client.

        Args:
            api_key: API key for authentication (None for public endpoints)
            base_url: Base URL for the API
            timeout: Request timeout in seconds
            max_retries: Maximum number of retries on rate limit (default: 3)
            retry_delay: Base delay in seconds for exponential backoff (default: 1.0)
            logger: Optional logger instance
            validate: Enable runtime validation using Pydantic models
        """
        self._api_key = api_key
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout
        self._max_retries = max_retries
        self._retry_delay = retry_delay
        self._logger = logger
        self._validate = validate

    def get(self, path: str, params: Optional[dict] = None, model_class: Optional[Type[T]] = None, accept: str = "application/json") -> Any:
        """Make a GET request."""
        return self._request("GET", path, params=params, model_class=model_class, accept=accept)

    def post(self, path: str, body: Optional[dict] = None, params: Optional[dict] = None, model_class: Optional[Type[T]] = None, accept: str = "application/json", idempotency_key: Optional[str] = None) -> Any:
        """Make a POST request."""
        return self._request("POST", path, body=body, params=params, model_class=model_class, accept=accept, idempotency_key=idempotency_key)

    def patch(self, path: str, body: Optional[dict] = None, params: Optional[dict] = None, model_class: Optional[Type[T]] = None, accept: str = "application/json", idempotency_key: Optional[str] = None) -> Any:
        """Make a PATCH request."""
        return self._request("PATCH", path, body=body, params=params, model_class=model_class, accept=accept, idempotency_key=idempotency_key)

    def put(self, path: str, body: Optional[dict] = None, params: Optional[dict] = None, model_class: Optional[Type[T]] = None, accept: str = "application/json", idempotency_key: Optional[str] = None) -> Any:
        """Make a PUT request."""
        return self._request("PUT", path, body=body, params=params, model_class=model_class, accept=accept, idempotency_key=idempotency_key)

    def delete(self, path: str, params: Optional[dict] = None, model_class: Optional[Type[T]] = None, accept: str = "application/json") -> Any:
        """Make a DELETE request."""
        return self._request("DELETE", path, params=params, model_class=model_class, accept=accept)

    def post_multipart(
        self,
        path: str,
        files: Optional[dict] = None,
        fields: Optional[dict] = None,
        params: Optional[dict] = None,
        idempotency_key: Optional[str] = None,
    ) -> Any:
        """POST with multipart/form-data for file uploads.

        Args:
            path: API path
            files: File parameters {param_name: file_path or file object or (filename, file_obj, content_type)}
            fields: Additional form fields
            params: Query parameters
            idempotency_key: Optional idempotency key
        """
        return self._multipart_request("POST", path, files=files, fields=fields, params=params, idempotency_key=idempotency_key)

    def patch_multipart(
        self,
        path: str,
        files: Optional[dict] = None,
        fields: Optional[dict] = None,
        params: Optional[dict] = None,
        idempotency_key: Optional[str] = None,
    ) -> Any:
        """PATCH with multipart/form-data for file uploads."""
        return self._multipart_request("PATCH", path, files=files, fields=fields, params=params, idempotency_key=idempotency_key)

    def put_multipart(
        self,
        path: str,
        files: Optional[dict] = None,
        fields: Optional[dict] = None,
        params: Optional[dict] = None,
        idempotency_key: Optional[str] = None,
    ) -> Any:
        """PUT with multipart/form-data for file uploads."""
        return self._multipart_request("PUT", path, files=files, fields=fields, params=params, idempotency_key=idempotency_key)

    def _request(
        self,
        method: str,
        path: str,
        body: Optional[dict] = None,
        params: Optional[dict] = None,
        model_class: Optional[Type[T]] = None,
        accept: str = "application/json",
        idempotency_key: Optional[str] = None,
    ) -> Any:
        """Execute an HTTP request with retry logic for idempotent methods."""
        url = self._build_url(path, params)
        headers = self._build_headers(accept, idempotency_key=idempotency_key)
        data = json.dumps(body).encode("utf-8") if body else None

        self._log_request(method, url)

        retries = 0
        while True:
            try:
                return self._execute_request(method, url, headers, data, model_class, accept)
            except RateLimitError as e:
                if method not in self.IDEMPOTENT_METHODS or retries >= self._max_retries:
                    raise

                retries += 1
                delay = e.retry_after if e.retry_after else self._retry_delay * (2 ** (retries - 1))
                self._log_retry(method, url, retries, delay)
                time.sleep(delay)

    def _execute_request(
        self,
        method: str,
        url: str,
        headers: dict,
        data: Optional[bytes],
        model_class: Optional[Type[T]] = None,
        accept: str = "application/json",
    ) -> Any:
        """Execute a single HTTP request."""
        req = urllib.request.Request(url, data=data, headers=headers, method=method)

        try:
            with urllib.request.urlopen(req, timeout=self._timeout) as response:
                return self._handle_response(response, model_class, accept)
        except urllib.error.HTTPError as e:
            return self._handle_error_response(e)
        except urllib.error.URLError as e:
            raise NetworkError(str(e.reason))
        except TimeoutError:
            raise NetworkError("Request timed out")

    def _build_url(self, path: str, params: Optional[dict]) -> str:
        """Build the full URL with query parameters."""
        url = f"{self._base_url}{path}"
        if params:
            # Filter out None values and flatten arrays
            query_params = []
            for key, value in params.items():
                if value is None:
                    continue
                if isinstance(value, list):
                    for item in value:
                        query_params.append((f"{key}[]", item))
                else:
                    query_params.append((key, value))
            if query_params:
                url = f"{url}?{urlencode(query_params)}"
        return url

    def _build_headers(self, accept: str = "application/json", idempotency_key: Optional[str] = None) -> dict:
        """Build request headers."""
        import sys

        headers = {
            "Content-Type": "application/json",
            "Accept": accept,
            "User-Agent": f"aho_sdk/{VERSION} python/{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}",
        }
        if self._api_key:
            headers["X-API-Key"] = self._api_key
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key
        return headers

    def _log_request(self, method: str, url: str) -> None:
        """Log request with credentials redacted."""
        if self._logger:
            self._logger.debug(f"[aho_sdk] {method} {url}")

    def _log_retry(self, method: str, url: str, attempt: int, delay: float) -> None:
        """Log retry attempt."""
        if self._logger:
            self._logger.warning(
                f"[aho_sdk] Retry {attempt}/{self._max_retries} for {method} {url} after {delay}s"
            )

    # Binary content types that should return raw bytes
    BINARY_CONTENT_TYPES = frozenset([
        "image/png", "image/jpeg", "image/gif", "image/webp", "image/svg+xml",
        "application/pdf", "application/octet-stream", "application/zip", "application/gzip",
    ])

    def _handle_response(self, response, model_class: Optional[Type[T]] = None, accept: str = "application/json") -> Any:
        """Handle successful response."""
        content_type = response.headers.get("Content-Type", "").split(";")[0].strip()
        body = response.read()

        if not body:
            return None

        # Return raw bytes for binary content types
        if self._is_binary_content_type(content_type) or self._is_binary_content_type(accept):
            return body

        # Decode as UTF-8 for text/JSON responses
        text_body = body.decode("utf-8")
        data = json.loads(text_body)

        # Parse response into Pydantic model if model_class provided
        if model_class is not None:
            try:
                from pydantic import ValidationError as PydanticValidationError

                return model_class.model_validate(data)
            except PydanticValidationError as e:
                if self._logger:
                    self._logger.warning(f"[aho_sdk] Response validation failed: {e}")
                # Return raw data on validation failure (graceful degradation)
                return data
            except ImportError:
                if self._logger:
                    self._logger.warning("[aho_sdk] Pydantic not installed, returning raw dict")
                return data

        return data

    def _is_binary_content_type(self, content_type: str) -> bool:
        """Check if content type is binary."""
        if not content_type:
            return False
        return any(content_type.startswith(bt) for bt in self.BINARY_CONTENT_TYPES) or content_type.startswith("image/")

    def _multipart_request(
        self,
        method: str,
        path: str,
        files: Optional[dict] = None,
        fields: Optional[dict] = None,
        params: Optional[dict] = None,
        idempotency_key: Optional[str] = None,
    ) -> Any:
        """Execute a multipart/form-data request."""
        import mimetypes
        import os
        import uuid

        url = self._build_url(path, params)
        boundary = f"----PythonMultipartClient{uuid.uuid4().hex}"

        body_parts = []

        # Add regular form fields
        for name, value in (fields or {}).items():
            body_parts.append(f"--{boundary}\r\n".encode())
            body_parts.append(f'Content-Disposition: form-data; name="{name}"\r\n\r\n'.encode())
            body_parts.append(f"{value}\r\n".encode())

        # Add file fields
        for name, file_info in (files or {}).items():
            file_obj, filename, content_type = self._normalize_file(file_info)

            body_parts.append(f"--{boundary}\r\n".encode())
            body_parts.append(f'Content-Disposition: form-data; name="{name}"; filename="{filename}"\r\n'.encode())
            body_parts.append(f"Content-Type: {content_type}\r\n\r\n".encode())

            # Read file content
            if hasattr(file_obj, "read"):
                body_parts.append(file_obj.read())
            else:
                body_parts.append(file_obj)

            body_parts.append(b"\r\n")

        body_parts.append(f"--{boundary}--\r\n".encode())
        body = b"".join(body_parts)

        headers = self._build_multipart_headers(boundary, idempotency_key)

        self._log_request(method, url)

        retries = 0
        while True:
            try:
                return self._execute_request(method, url, headers, body, None, "application/json")
            except RateLimitError as e:
                if method not in self.IDEMPOTENT_METHODS or retries >= self._max_retries:
                    raise

                retries += 1
                delay = e.retry_after if e.retry_after else self._retry_delay * (2 ** (retries - 1))
                self._log_retry(method, url, retries, delay)
                time.sleep(delay)

    def _normalize_file(self, file_info):
        """Normalize file info to (file_obj, filename, content_type)."""
        import mimetypes
        import os
        from pathlib import Path

        if isinstance(file_info, str):
            # Path string
            file_obj = open(file_info, "rb")
            filename = os.path.basename(file_info)
            content_type = self._mime_type_for(filename)
            return file_obj, filename, content_type
        elif isinstance(file_info, Path):
            # pathlib.Path
            file_obj = file_info.open("rb")
            filename = file_info.name
            content_type = self._mime_type_for(filename)
            return file_obj, filename, content_type
        elif isinstance(file_info, tuple):
            # Tuple of (filename, file_obj, content_type)
            if len(file_info) == 3:
                return file_info[1], file_info[0], file_info[2]
            elif len(file_info) == 2:
                return file_info[1], file_info[0], self._mime_type_for(file_info[0])
            else:
                raise ValueError("File tuple must have 2 or 3 elements: (filename, file_obj[, content_type])")
        elif hasattr(file_info, "read"):
            # File-like object
            filename = getattr(file_info, "name", "file")
            if isinstance(filename, str):
                filename = os.path.basename(filename)
            else:
                filename = "file"
            content_type = self._mime_type_for(filename)
            return file_info, filename, content_type
        else:
            raise ValueError(f"Unsupported file type: {type(file_info)}")

    def _build_multipart_headers(self, boundary: str, idempotency_key: Optional[str] = None) -> dict:
        """Build headers for multipart request."""
        import sys

        headers = {
            "Content-Type": f"multipart/form-data; boundary={boundary}",
            "Accept": "application/json",
            "User-Agent": f"aho_sdk/{VERSION} python/{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}",
        }
        if self._api_key:
            headers["X-API-Key"] = self._api_key
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key
        return headers

    # Auto-detect MIME type from file extension
    MIME_TYPES = {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".gif": "image/gif",
        ".webp": "image/webp",
        ".svg": "image/svg+xml",
        ".pdf": "application/pdf",
        ".zip": "application/zip",
        ".gz": "application/gzip",
        ".json": "application/json",
        ".xml": "application/xml",
        ".txt": "text/plain",
        ".html": "text/html",
        ".css": "text/css",
        ".js": "application/javascript",
    }

    def _mime_type_for(self, filename: str) -> str:
        """Get MIME type from filename extension."""
        import os
        ext = os.path.splitext(filename)[1].lower()
        return self.MIME_TYPES.get(ext, "application/octet-stream")

    def _handle_error_response(self, error: urllib.error.HTTPError) -> Any:
        """Handle error response and raise appropriate exception."""
        body = error.read().decode("utf-8")
        status = error.code
        request_id = error.headers.get("X-Request-Id")
        retry_after = error.headers.get("Retry-After")

        error_classes = {
            400: BadRequestError,
            401: AuthenticationError,
            403: ForbiddenError,
            404: NotFoundError,
            409: ConflictError,
            422: ValidationError,
            429: RateLimitError,
        }

        if status in error_classes:
            exc_class = error_classes[status]
            if status == 429:
                raise exc_class(body, status, request_id, float(retry_after) if retry_after else None)
            raise exc_class(body, status, request_id)
        elif 500 <= status < 600:
            raise ServerError(body, status, request_id)
        else:
            raise ApiError(body, status, request_id)
