"""Issue and manage verifiable credentials"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .http_client import HttpClient
from .page import Page
from .cursor_page import CursorPage
from . import types as Types
from . import models as Models

class Issuer:
    """Issue and manage verifiable credentials

    Example:
        client = Issuer(api_key=os.environ["AHO_ISSUER_API_KEY"])
        client.automations.list()
        client.credentials.list()
        client.revoke_batch.list()
        client.suspend_batch.list()
        client.reinstate_batch.list()
        client.data_source_mappings.list()
        client.data_sources.list()
        client.offers.list()
        client.schemas.list()
        client.verify.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: int = 30,
        logger: Any = None,
    ):
        """Initialize the client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
        """
        self._client = HttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
        )
        self._automations = _AutomationsResource(self._client)
        self._credentials = _CredentialsResource(self._client)
        self._revoke_batch = _RevokeBatchResource(self._client)
        self._suspend_batch = _SuspendBatchResource(self._client)
        self._reinstate_batch = _ReinstateBatchResource(self._client)
        self._data_source_mappings = _DataSourceMappingsResource(self._client)
        self._data_sources = _DataSourcesResource(self._client)
        self._offers = _OffersResource(self._client)
        self._schemas = _SchemasResource(self._client)
        self._verify = _VerifyResource(self._client)

    @property
    def automations(self) -> "_AutomationsResource":
        """Automations resource."""
        return self._automations

    @property
    def credentials(self) -> "_CredentialsResource":
        """Credentials resource."""
        return self._credentials

    @property
    def revoke_batch(self) -> "_RevokeBatchResource":
        """Revoke_batch resource."""
        return self._revoke_batch

    @property
    def suspend_batch(self) -> "_SuspendBatchResource":
        """Suspend_batch resource."""
        return self._suspend_batch

    @property
    def reinstate_batch(self) -> "_ReinstateBatchResource":
        """Reinstate_batch resource."""
        return self._reinstate_batch

    @property
    def data_source_mappings(self) -> "_DataSourceMappingsResource":
        """Data_source_mappings resource."""
        return self._data_source_mappings

    @property
    def data_sources(self) -> "_DataSourcesResource":
        """Data_sources resource."""
        return self._data_sources

    @property
    def offers(self) -> "_OffersResource":
        """Offers resource."""
        return self._offers

    @property
    def schemas(self) -> "_SchemasResource":
        """Schemas resource."""
        return self._schemas

    @property
    def verify(self) -> "_VerifyResource":
        """Verify resource."""
        return self._verify

class _AutomationsResource:
    """Automations resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def get_webhook(self, automation_id: str) -> Optional[Models.Automationwebhook]:
        """Get webhook configuration"""
        return self._client.get(f"/v1/issuer/automations/{automation_id}/webhook", model_class=Models.Automationwebhook)

    def create_webhook(self, automation_id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Automationwebhook]:
        """Generate webhook token"""
        return self._client.post(f"/v1/issuer/automations/{automation_id}/webhook", idempotency_key=idempotency_key, model_class=Models.Automationwebhook)

    def delete_webhook(self, automation_id: str) -> Optional[dict]:
        """Revoke webhook token"""
        return self._client.delete(f"/v1/issuer/automations/{automation_id}/webhook", model_class=None)

    def create(self, body: Optional[Types.Createautomationparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialautomation]:
        """Create an automation"""
        return self._client.post(f"/v1/issuer/automations", body=body, idempotency_key=idempotency_key, model_class=Models.Credentialautomation)

    def list(self, status: Optional[str] = None, trigger_mode: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Credentialautomation]:
        """List automations"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/issuer/automations", params={"status": status, "trigger_mode": trigger_mode, "page": p, "per_page": per_page}, model_class=Models.Credentialautomation)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, id: str) -> Optional[Models.Credentialautomation]:
        """Get automation details"""
        return self._client.get(f"/v1/issuer/automations/{id}", model_class=Models.Credentialautomation)

    def update(self, id: str, body: Optional[Types.Updateautomationparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialautomation]:
        """Update an automation"""
        return self._client.patch(f"/v1/issuer/automations/{id}", body=body, idempotency_key=idempotency_key, model_class=Models.Credentialautomation)

    def delete(self, id: str) -> Optional[dict]:
        """Delete an automation"""
        return self._client.delete(f"/v1/issuer/automations/{id}", model_class=None)

    def trigger(self, id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Automationtriggerresult]:
        """Trigger an automation"""
        return self._client.post(f"/v1/issuer/automations/{id}/trigger", idempotency_key=idempotency_key, model_class=Models.Automationtriggerresult)

    def pause(self, id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialautomation]:
        """Pause an automation"""
        return self._client.post(f"/v1/issuer/automations/{id}/pause", idempotency_key=idempotency_key, model_class=Models.Credentialautomation)

    def resume(self, id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialautomation]:
        """Resume an automation"""
        return self._client.post(f"/v1/issuer/automations/{id}/resume", idempotency_key=idempotency_key, model_class=Models.Credentialautomation)

class _CredentialsResource:
    """Credentials resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Createcredentialparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialissuance]:
        """Issue a new credential"""
        return self._client.post(f"/v1/issuer/credentials", body=body, idempotency_key=idempotency_key, model_class=Models.Credentialissuance)

    def list(self, status: Optional[str] = None, schema: Optional[str] = None, subject_identifier: Optional[str] = None, issued_after: Optional[str] = None, issued_before: Optional[str] = None, expires_after: Optional[str] = None, expires_before: Optional[str] = None, sort: Optional[str] = "issued_at", direction: Optional[str] = "desc", page: Optional[int] = 1, per_page: Optional[int] = 25) -> Page[Models.Credentialissuance]:
        """List credentials"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/issuer/credentials", params={"status": status, "schema": schema, "subject_identifier": subject_identifier, "issued_after": issued_after, "issued_before": issued_before, "expires_after": expires_after, "expires_before": expires_before, "sort": sort, "direction": direction, "page": p, "per_page": per_page}, model_class=Models.Credentialissuance)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, uuid: str) -> Optional[Models.Credentialissuance]:
        """Get issued credential details"""
        return self._client.get(f"/v1/issuer/credentials/{uuid}", model_class=Models.Credentialissuance)

    def revoke(self, uuid: str, body: Optional[Types.Revokecredentialparams] = None, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Revoke a credential"""
        return self._client.post(f"/v1/issuer/credentials/{uuid}/revoke", body=body, idempotency_key=idempotency_key, model_class=None)

    def suspend(self, uuid: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Suspend a credential"""
        return self._client.post(f"/v1/issuer/credentials/{uuid}/suspend", idempotency_key=idempotency_key, model_class=None)

    def reinstate(self, uuid: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Reinstate a suspended credential"""
        return self._client.post(f"/v1/issuer/credentials/{uuid}/reinstate", idempotency_key=idempotency_key, model_class=None)

    def status(self, uuid: str) -> Optional[dict]:
        """Get credential status"""
        return self._client.get(f"/v1/issuer/credentials/{uuid}/status", model_class=None)

    def history(self, uuid: str) -> Optional[dict]:
        """Get credential history"""
        return self._client.get(f"/v1/issuer/credentials/{uuid}/history", model_class=None)

class _RevokeBatchResource:
    """Revoke_batch resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Revokebatchparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Batchoperationresult]:
        """Revoke multiple credentials"""
        return self._client.post(f"/v1/issuer/credentials/revoke_batch", body=body, idempotency_key=idempotency_key, model_class=Models.Batchoperationresult)

class _SuspendBatchResource:
    """Suspend_batch resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Suspendbatchparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Batchoperationresult]:
        """Suspend multiple credentials"""
        return self._client.post(f"/v1/issuer/credentials/suspend_batch", body=body, idempotency_key=idempotency_key, model_class=Models.Batchoperationresult)

class _ReinstateBatchResource:
    """Reinstate_batch resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Reinstatebatchparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Batchoperationresult]:
        """Reinstate multiple credentials"""
        return self._client.post(f"/v1/issuer/credentials/reinstate_batch", body=body, idempotency_key=idempotency_key, model_class=Models.Batchoperationresult)

class _DataSourceMappingsResource:
    """Data_source_mappings resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Createdatasourcemappingparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Datasourcemapping]:
        """Create a data source mapping"""
        return self._client.post(f"/v1/issuer/data_source_mappings", body=body, idempotency_key=idempotency_key, model_class=Models.Datasourcemapping)

    def list(self, data_source: Optional[str] = None, credential_schema: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Datasourcemapping]:
        """List data source mappings"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/issuer/data_source_mappings", params={"data_source": data_source, "credential_schema": credential_schema, "page": p, "per_page": per_page}, model_class=Models.Datasourcemapping)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, id: str) -> Optional[Models.Datasourcemapping]:
        """Get mapping details"""
        return self._client.get(f"/v1/issuer/data_source_mappings/{id}", model_class=Models.Datasourcemapping)

    def update(self, id: str, body: Optional[Types.Updatedatasourcemappingparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Datasourcemapping]:
        """Update a mapping"""
        return self._client.patch(f"/v1/issuer/data_source_mappings/{id}", body=body, idempotency_key=idempotency_key, model_class=Models.Datasourcemapping)

    def delete(self, id: str) -> Optional[dict]:
        """Delete a mapping"""
        return self._client.delete(f"/v1/issuer/data_source_mappings/{id}", model_class=None)

class _DataSourcesResource:
    """Data_sources resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Createdatasourceparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Datasource]:
        """Create a data source"""
        return self._client.post(f"/v1/issuer/data_sources", body=body, idempotency_key=idempotency_key, model_class=Models.Datasource)

    def list(self, status: Optional[str] = None, source_type: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Datasource]:
        """List data sources"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/issuer/data_sources", params={"status": status, "source_type": source_type, "page": p, "per_page": per_page}, model_class=Models.Datasource)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, id: str) -> Optional[Models.Datasource]:
        """Get data source details"""
        return self._client.get(f"/v1/issuer/data_sources/{id}", model_class=Models.Datasource)

    def update(self, id: str, body: Optional[Types.Updatedatasourceparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Datasource]:
        """Update a data source"""
        return self._client.patch(f"/v1/issuer/data_sources/{id}", body=body, idempotency_key=idempotency_key, model_class=Models.Datasource)

    def delete(self, id: str) -> Optional[dict]:
        """Delete a data source"""
        return self._client.delete(f"/v1/issuer/data_sources/{id}", model_class=None)

    def test(self, id: str, idempotency_key: Optional[str] = None) -> Optional[Models.Datasourcetestresult]:
        """Test data source connection"""
        return self._client.post(f"/v1/issuer/data_sources/{id}/test", idempotency_key=idempotency_key, model_class=Models.Datasourcetestresult)

class _OffersResource:
    """Offers resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def list(self, page: Optional[int] = None, per_page: Optional[int] = None, status: Optional[str] = None, created_after: Optional[str] = None, created_before: Optional[str] = None, expires_after: Optional[str] = None, expires_before: Optional[str] = None, schema: Optional[str] = None, subject_identifier: Optional[str] = None, sort: Optional[str] = None, direction: Optional[str] = None) -> Page[Models.Credentialoffer]:
        """List credential offers"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/issuer/offers", params={"page": p, "per_page": per_page, "status": status, "created_after": created_after, "created_before": created_before, "expires_after": expires_after, "expires_before": expires_before, "schema": schema, "subject_identifier": subject_identifier, "sort": sort, "direction": direction}, model_class=Models.Credentialoffer)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def create(self, body: Optional[Types.Createofferparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Credentialofferresult]:
        """Create a credential offer"""
        return self._client.post(f"/v1/issuer/offers", body=body, idempotency_key=idempotency_key, model_class=Models.Credentialofferresult)

    def get(self, uuid: str) -> Optional[Models.Credentialoffer]:
        """Get credential offer details"""
        return self._client.get(f"/v1/issuer/offers/{uuid}", model_class=Models.Credentialoffer)

    def revoke(self, uuid: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Revoke a credential offer"""
        return self._client.post(f"/v1/issuer/offers/{uuid}/revoke", idempotency_key=idempotency_key, model_class=None)

class _SchemasResource:
    """Schemas resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Createschemaparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Issuercredentialschema]:
        """Create a credential schema"""
        return self._client.post(f"/v1/issuer/schemas", body=body, idempotency_key=idempotency_key, model_class=Models.Issuercredentialschema)

    def list(self, status: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Issuercredentialschema]:
        """List issuer credential schemas"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/issuer/schemas", params={"status": status, "page": p, "per_page": per_page}, model_class=Models.Issuercredentialschema)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, id: str) -> Optional[Models.Issuercredentialschema]:
        """Get credential schema details"""
        return self._client.get(f"/v1/issuer/schemas/{id}", model_class=Models.Issuercredentialschema)

    def update(self, id: str, body: Optional[Types.Updateschemaparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Issuercredentialschema]:
        """Update a draft credential schema"""
        return self._client.patch(f"/v1/issuer/schemas/{id}", body=body, idempotency_key=idempotency_key, model_class=Models.Issuercredentialschema)

    def delete(self, id: str) -> Optional[dict]:
        """Delete a draft credential schema"""
        return self._client.delete(f"/v1/issuer/schemas/{id}", model_class=None)

    def activate(self, id: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Activate a draft credential schema"""
        return self._client.post(f"/v1/issuer/schemas/{id}/activate", idempotency_key=idempotency_key, model_class=None)

    def archive(self, id: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Archive an active credential schema"""
        return self._client.post(f"/v1/issuer/schemas/{id}/archive", idempotency_key=idempotency_key, model_class=None)

class _VerifyResource:
    """Verify resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def get(self, uuid: str) -> Optional[Models.Verificationresult]:
        """Verify a credential by UUID"""
        return self._client.get(f"/v1/issuer/verify/{uuid}", model_class=Models.Verificationresult)

    def create(self, body: Optional[Types.Verifycredentialparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Verificationresult]:
        """Verify a credential"""
        return self._client.post(f"/v1/issuer/verify", body=body, idempotency_key=idempotency_key, model_class=Models.Verificationresult)

