"""Pagination support with lazy iteration."""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Callable, Iterator, Optional

class Page:
    """Paginated response with lazy iteration support.

    Example:
        # Iterate through all pages
        page = issuer.credentials.list()
        for credential in page:
            print(credential["uuid"])

        # Manual pagination
        page = issuer.credentials.list()
        while page:
            for c in page.data:
                print(c["uuid"])
            page = page.next_page()
    """

    def __init__(
        self,
        data: list[dict],
        meta: dict,
        fetch_next: Callable[[int], Optional["Page"]],
    ):
        """Initialize a page.

        Args:
            data: Items on this page.
            meta: Pagination metadata (current_page, per_page, total_count, total_pages).
            fetch_next: Callable to fetch the next page.
        """
        self._data = data
        self._meta = meta
        self._fetch_next = fetch_next

    @property
    def data(self) -> list[dict]:
        """Items on this page."""
        return self._data

    @property
    def meta(self) -> dict:
        """Pagination metadata."""
        return self._meta

    @property
    def current_page(self) -> int:
        """Current page number."""
        return self._meta.get("current_page", 1)

    @property
    def total_pages(self) -> int:
        """Total number of pages."""
        return self._meta.get("total_pages", 1)

    @property
    def total_count(self) -> int:
        """Total number of items across all pages."""
        return self._meta.get("total_count", len(self._data))

    @property
    def per_page(self) -> int:
        """Number of items per page."""
        return self._meta.get("per_page", 25)

    def is_last_page(self) -> bool:
        """Check if this is the last page."""
        return self.current_page >= self.total_pages

    def next_page(self) -> Optional["Page"]:
        """Fetch the next page.

        Returns:
            Next page or None if this is the last page.
        """
        if self.is_last_page():
            return None
        return self._fetch_next(self.current_page + 1)

    def __iter__(self) -> Iterator[dict]:
        """Iterate through all items across all pages (lazy loading)."""
        page: Optional[Page] = self
        while page is not None:
            yield from page.data
            page = page.next_page()

    def __len__(self) -> int:
        """Return number of items on this page."""
        return len(self._data)

    def __bool__(self) -> bool:
        """Return True if there are items on this page."""
        return len(self._data) > 0
