"""Browse and retrieve credential schemas"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .http_client import HttpClient
from .page import Page
from .cursor_page import CursorPage
from . import types as Types
from . import models as Models

class Schemas:
    """Browse and retrieve credential schemas

    Example:
        client = Schemas(api_key=os.environ["AHO_SCHEMAS_API_KEY"])
        client.render_templates.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: int = 30,
        logger: Any = None,
    ):
        """Initialize the client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
        """
        self._client = HttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
        )
        self._render_templates = _RenderTemplatesResource(self._client)

    @property
    def render_templates(self) -> "_RenderTemplatesResource":
        """Render_templates resource."""
        return self._render_templates

class _RenderTemplatesResource:
    """Render_templates resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def list(self, schema_id: str) -> Page[Models.Rendertemplate]:
        """List render templates"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/schemas/{schema_id}/render_templates", model_class=Models.Rendertemplate)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(1)

    def create(self, schema_id: str, body: Optional[Types.Createrendertemplateparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Rendertemplate]:
        """Create render template"""
        return self._client.post(f"/v1/schemas/{schema_id}/render_templates", body=body, idempotency_key=idempotency_key, model_class=Models.Rendertemplate)

    def get(self, schema_id: str, id: str) -> Optional[Models.Rendertemplate]:
        """Get render template"""
        return self._client.get(f"/v1/schemas/{schema_id}/render_templates/{id}", model_class=Models.Rendertemplate)

    def update(self, schema_id: str, id: str, body: Optional[Types.Updaterendertemplateparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Rendertemplate]:
        """Update render template"""
        return self._client.patch(f"/v1/schemas/{schema_id}/render_templates/{id}", body=body, idempotency_key=idempotency_key, model_class=Models.Rendertemplate)

    def delete(self, schema_id: str, id: str) -> Optional[dict]:
        """Delete render template"""
        return self._client.delete(f"/v1/schemas/{schema_id}/render_templates/{id}", model_class=None)

    def validate(self, schema_id: str, body: Optional[Types.Validaterendertemplateparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Rendertemplatevalidationresult]:
        """Validate template"""
        return self._client.post(f"/v1/schemas/{schema_id}/render_templates/validate", body=body, idempotency_key=idempotency_key, model_class=Models.Rendertemplatevalidationresult)

