"""System health and status endpoints"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .http_client import HttpClient
from .page import Page
from .cursor_page import CursorPage
from . import types as Types
from . import models as Models

class System:
    """System health and status endpoints

    Example:
        client = System(api_key=os.environ["AHO_SYSTEM_API_KEY"])
        client.health.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: int = 30,
        logger: Any = None,
    ):
        """Initialize the client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
        """
        self._client = HttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
        )
        self._health = _HealthResource(self._client)

    @property
    def health(self) -> "_HealthResource":
        """Health resource."""
        return self._health

class _HealthResource:
    """Health resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def get(self) -> Optional[dict]:
        """Health check"""
        return self._client.get(f"/v1/health", model_class=None)

