"""Public endpoints (no authentication required)"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .http_client import HttpClient
from .page import Page
from .cursor_page import CursorPage
from . import types as Types
from . import models as Models

class Unauthenticated:
    """Public endpoints (no authentication required)

    Example:
        client = Unauthenticated()
        client.schemas.list()
    """

    def __init__(
        self,
        base_url: str = "https://api.aho.com",
        timeout: int = 30,
        logger: Any = None,
    ):
        """Initialize the client.

        Args:
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
        """
        self._client = HttpClient(
            api_key=None,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
        )
        self._schemas = _SchemasResource(self._client)

    @property
    def schemas(self) -> "_SchemasResource":
        """Schemas resource."""
        return self._schemas

class _SchemasResource:
    """Schemas resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def list(self, category: Optional[str] = None, tag: Optional[str] = None, q: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Credentialschema]:
        """Browse public credential schemas"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/schemas", params={"category": category, "tag": tag, "q": q, "page": p, "per_page": per_page}, model_class=Models.Credentialschema)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, slug: str) -> Page[Models.Credentialschema]:
        """Get schema details"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/schemas/{slug}", model_class=Models.Credentialschema)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(1)

