"""Create presentation requests and verify credentials"""
# Auto-generated by bin/generate_sdks.rb - DO NOT EDIT

from __future__ import annotations

from typing import Any, Optional

from .http_client import HttpClient
from .page import Page
from .cursor_page import CursorPage
from . import types as Types
from . import models as Models

class Verifier:
    """Create presentation requests and verify credentials

    Example:
        client = Verifier(api_key=os.environ["AHO_VERIFIER_API_KEY"])
        client.presentations.list()
        client.dc_sessions.list()
        client.render.list()
        client.requests.list()
        client.responses.list()
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.aho.com",
        timeout: int = 30,
        logger: Any = None,
    ):
        """Initialize the client.

        Args:
            api_key: API key for authentication.
            base_url: Base URL (default: https://api.aho.com).
            timeout: Request timeout in seconds (default: 30).
            logger: Optional logger for debugging.
        """
        self._client = HttpClient(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
            logger=logger,
        )
        self._presentations = _PresentationsResource(self._client)
        self._dc_sessions = _DcSessionsResource(self._client)
        self._render = _RenderResource(self._client)
        self._requests = _RequestsResource(self._client)
        self._responses = _ResponsesResource(self._client)

    @property
    def presentations(self) -> "_PresentationsResource":
        """Presentations resource."""
        return self._presentations

    @property
    def dc_sessions(self) -> "_DcSessionsResource":
        """Dc_sessions resource."""
        return self._dc_sessions

    @property
    def render(self) -> "_RenderResource":
        """Render resource."""
        return self._render

    @property
    def requests(self) -> "_RequestsResource":
        """Requests resource."""
        return self._requests

    @property
    def responses(self) -> "_ResponsesResource":
        """Responses resource."""
        return self._responses

class _PresentationsResource:
    """Presentations resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def verify(self, body: Optional[Types.Verifypresentationparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Presentationverifyresult]:
        """Verify a presentation"""
        return self._client.post(f"/v1/verifier/presentations/verify", body=body, idempotency_key=idempotency_key, model_class=Models.Presentationverifyresult)

class _DcSessionsResource:
    """Dc_sessions resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Createdcsessionparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Dcapisessioncreateresponse]:
        """Create a DC API session"""
        return self._client.post(f"/v1/verifier/dc_sessions", body=body, idempotency_key=idempotency_key, model_class=Models.Dcapisessioncreateresponse)

    def get(self, id: str) -> Optional[Models.Dcapisession]:
        """Get DC API session status"""
        return self._client.get(f"/v1/verifier/dc_sessions/{id}", model_class=Models.Dcapisession)

    def verify(self, id: str, body: Optional[Types.Verifydcsessionparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Dcapisessionverifyresponse]:
        """Verify a DC API session"""
        return self._client.post(f"/v1/verifier/dc_sessions/{id}/verify", body=body, idempotency_key=idempotency_key, model_class=Models.Dcapisessionverifyresponse)

class _RenderResource:
    """Render resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def list(self, id: str, format: Optional[str] = None) -> Optional[dict]:
        """Render verified claims as visual credential"""
        return self._client.get(f"/v1/verifier/dc_sessions/{id}/render", params={"format": format}, model_class=None)

    def create(self, body: Optional[Types.Renderparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Renderresponse]:
        """Render claims as visual credential"""
        return self._client.post(f"/v1/verifier/render", body=body, idempotency_key=idempotency_key, model_class=Models.Renderresponse)

class _RequestsResource:
    """Requests resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def create(self, body: Optional[Types.Createpresentationrequestparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Presentationrequest]:
        """Create a presentation request"""
        return self._client.post(f"/v1/verifier/requests", body=body, idempotency_key=idempotency_key, model_class=Models.Presentationrequest)

    def list(self, status: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Presentationrequest]:
        """List presentation requests"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/verifier/requests", params={"status": status, "page": p, "per_page": per_page}, model_class=Models.Presentationrequest)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, uuid: str) -> Optional[Models.Presentationrequest]:
        """Get presentation request details"""
        return self._client.get(f"/v1/verifier/requests/{uuid}", model_class=Models.Presentationrequest)

    def update(self, uuid: str, body: Optional[Types.Updatepresentationrequestparams] = None, idempotency_key: Optional[str] = None) -> Optional[Models.Presentationrequest]:
        """Update a draft presentation request"""
        return self._client.patch(f"/v1/verifier/requests/{uuid}", body=body, idempotency_key=idempotency_key, model_class=Models.Presentationrequest)

    def delete(self, uuid: str) -> Optional[dict]:
        """Delete a draft presentation request"""
        return self._client.delete(f"/v1/verifier/requests/{uuid}", model_class=None)

    def activate(self, uuid: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Activate a draft presentation request"""
        return self._client.post(f"/v1/verifier/requests/{uuid}/activate", idempotency_key=idempotency_key, model_class=None)

    def close(self, uuid: str, idempotency_key: Optional[str] = None) -> Optional[dict]:
        """Close an active presentation request"""
        return self._client.post(f"/v1/verifier/requests/{uuid}/close", idempotency_key=idempotency_key, model_class=None)

    def qr_code(self, uuid: str, format: Optional[str] = None, output_format: str = "svg") -> bytes:
        """Get QR code for presentation request"""
        format_map = {{"svg": "image/svg+xml", "png": "image/png", "json": "application/json"}}
        accept = format_map.get(output_format, list(format_map.values())[0])
        return self._client.get(f"/v1/verifier/requests/{uuid}/qr_code", params={"format": format}, accept=accept)

class _ResponsesResource:
    """Responses resource operations."""

    def __init__(self, client: HttpClient):
        self._client = client

    def list(self, request_uuid: str, status: Optional[str] = None, page: Optional[int] = None, per_page: Optional[int] = None) -> Page[Models.Presentationresponse]:
        """List responses for a presentation request"""
        def fetch_page(p: int) -> Page:
            response = self._client.get(f"/v1/verifier/requests/{request_uuid}/responses", params={"status": status, "page": p, "per_page": per_page}, model_class=Models.Presentationresponse)
            return Page(data=response["data"], meta=response["meta"], fetch_next=fetch_page)
        return fetch_page(page)

    def get(self, request_uuid: str, uuid: str) -> Optional[Models.Presentationresponse]:
        """Get response details"""
        return self._client.get(f"/v1/verifier/requests/{request_uuid}/responses/{uuid}", model_class=Models.Presentationresponse)

